CREATE TABLE airlines (
   airline_name TEXT,
   airline_code varchar(3),
   airline_name_translations_en TEXT,
   PRIMARY KEY (airline_code)
);

INSERT INTO airlines VALUES(NULL,'FM','Shanghai Airlines');
INSERT INTO airlines VALUES(NULL,'M3','North Flying');
INSERT INTO airlines VALUES(NULL,'B2','Belavia');
INSERT INTO airlines VALUES(NULL,'P8','Air Mekong');
INSERT INTO airlines VALUES(NULL,'EL','Ellinair');
INSERT INTO airlines VALUES(NULL,'SV','Saudia');
INSERT INTO airlines VALUES(NULL,'AF','Air France');
INSERT INTO airlines VALUES(NULL,'V1','IBS Software Services Americas, Inc.');
INSERT INTO airlines VALUES(NULL,'DE','Condor');
INSERT INTO airlines VALUES(NULL,'2D','Eastern Airlines, LLC');
INSERT INTO airlines VALUES(NULL,'AI','Air India');
INSERT INTO airlines VALUES(NULL,'WX','Cityjet');
INSERT INTO airlines VALUES(NULL,'DN','Norwegian Air');
INSERT INTO airlines VALUES(NULL,'2I','Star Peru');
INSERT INTO airlines VALUES(NULL,'HZ','Aurora');
INSERT INTO airlines VALUES(NULL,'OY','Andes Lineas Aereas');
INSERT INTO airlines VALUES(NULL,'5A','Alpine Aviation Inc.');
INSERT INTO airlines VALUES(NULL,'AK','AirAsia');
INSERT INTO airlines VALUES(NULL,'PB','Provincial Airlines');
INSERT INTO airlines VALUES(NULL,'B0','La Compagnie');
INSERT INTO airlines VALUES(NULL,'JQ','Jetstar');
INSERT INTO airlines VALUES(NULL,'UL','Srilankan Airlines');
INSERT INTO airlines VALUES(NULL,'7K','MetroJet');
INSERT INTO airlines VALUES(NULL,'6O','Orbest');
INSERT INTO airlines VALUES(NULL,'PS','UIA');
INSERT INTO airlines VALUES(NULL,'WG','Sunwing Airlines');
INSERT INTO airlines VALUES(NULL,'W8','Cargojet Airways Ltd.');
INSERT INTO airlines VALUES(NULL,'CX','Cathay Pacific');
INSERT INTO airlines VALUES(NULL,'1M','JSC Transport Automated InformationSystems - TAIS');
INSERT INTO airlines VALUES(NULL,'Z4','Zagros Air Co.');
INSERT INTO airlines VALUES(NULL,'8P','Pacific Coastal Airlines');
INSERT INTO airlines VALUES(NULL,'EZ','Sun-Air of Scandinavia');
INSERT INTO airlines VALUES(NULL,'2A','Deutsche Bahn AG');
INSERT INTO airlines VALUES(NULL,'D5','DHL Aero Expreso S.A.');
INSERT INTO airlines VALUES(NULL,'3H','Air Inuit');
INSERT INTO airlines VALUES(NULL,'F2','Safarilink Aviation');
INSERT INTO airlines VALUES(NULL,'LO','LOT Polish Airlines');
INSERT INTO airlines VALUES(NULL,'8J','EcoJet');
INSERT INTO airlines VALUES(NULL,'1R','Bird Information Systems Private Limited');
INSERT INTO airlines VALUES(NULL,'VC','Charter Air Transport, Inc.');
INSERT INTO airlines VALUES(NULL,'KE','Korean Air');
INSERT INTO airlines VALUES(NULL,'SC','Shandong Airlines');
INSERT INTO airlines VALUES(NULL,'55','Buta Airways');
INSERT INTO airlines VALUES(NULL,'XT','Indonesia AirAsia Extra, PT');
INSERT INTO airlines VALUES(NULL,'SB','Aircalin');
INSERT INTO airlines VALUES(NULL,'JM','Air Jamaica');
INSERT INTO airlines VALUES(NULL,'FL','Airtran Airways');
INSERT INTO airlines VALUES(NULL,'V0','Conviasa');
INSERT INTO airlines VALUES(NULL,'UO','Hong Kong Express Airways');
INSERT INTO airlines VALUES(NULL,'BC','Skymark Airlines');
INSERT INTO airlines VALUES(NULL,'UN','Transaero Airlines');
INSERT INTO airlines VALUES(NULL,'2H','Thalys International');
INSERT INTO airlines VALUES(NULL,'VY','Vueling');
INSERT INTO airlines VALUES(NULL,'LT','Air Lituanica');
INSERT INTO airlines VALUES(NULL,'W7','Wings of Lebanon S.a.l');
INSERT INTO airlines VALUES(NULL,'HH','Taban Airlines');
INSERT INTO airlines VALUES(NULL,'HM','Air Seychelles');
INSERT INTO airlines VALUES(NULL,'XP','TEM Enterprises');
INSERT INTO airlines VALUES(NULL,'YY','Major Airline');
INSERT INTO airlines VALUES(NULL,'NH','All Nippon Airways');
INSERT INTO airlines VALUES(NULL,'OL','Polynesian Airlines');
INSERT INTO airlines VALUES(NULL,'GT','Vista Georgia');
INSERT INTO airlines VALUES(NULL,'9P','Air Arabia Jordan');
INSERT INTO airlines VALUES(NULL,'Z7','Amaszonas');
INSERT INTO airlines VALUES(NULL,'EJ','New England Airlines');
INSERT INTO airlines VALUES(NULL,'GF','Gulf Air');
INSERT INTO airlines VALUES(NULL,'RT','UVT Aero');
INSERT INTO airlines VALUES(NULL,'YP','Perimeter Aviation Ltd.');
INSERT INTO airlines VALUES(NULL,'BY','Thomson Airways');
INSERT INTO airlines VALUES(NULL,'1H','JSC "Sirena-Travel"');
INSERT INTO airlines VALUES(NULL,'VP','Villa Air Pvt. Ltd. dba Villa Air');
INSERT INTO airlines VALUES(NULL,'ER','Air East');
INSERT INTO airlines VALUES(NULL,'IE','Solomon Airlines');
INSERT INTO airlines VALUES(NULL,'9N','Tropic Air Limited');
INSERT INTO airlines VALUES(NULL,'1A','Amadeus IT Group SA');
INSERT INTO airlines VALUES(NULL,'5Q','BQB Lineas Aereas');
INSERT INTO airlines VALUES(NULL,'HJ','Hellas Jet');
INSERT INTO airlines VALUES(NULL,'L7','Linea Aerea Carguera de Colombia S.A.');
INSERT INTO airlines VALUES(NULL,'XG','SunExpress Deutschland');
INSERT INTO airlines VALUES(NULL,'S5','Shuttle America');
INSERT INTO airlines VALUES(NULL,'UQ','Urumqi Air');
INSERT INTO airlines VALUES(NULL,'GW','GetJet');
INSERT INTO airlines VALUES(NULL,'HT','Ningxia Cargo Airlines CO.,LTD');
INSERT INTO airlines VALUES(NULL,'RL','Royal Flight');
INSERT INTO airlines VALUES(NULL,'U3','As Avies');
INSERT INTO airlines VALUES(NULL,'NS','Hebei Airlines');
INSERT INTO airlines VALUES(NULL,'MU','China Eastern Airlines');
INSERT INTO airlines VALUES(NULL,'XQ','Sun Express');
INSERT INTO airlines VALUES(NULL,'GK','Jetstar Japan');
INSERT INTO airlines VALUES(NULL,'4R','CJSC Royal Flight airlines');
INSERT INTO airlines VALUES(NULL,'DR','Ruili Airlines');
INSERT INTO airlines VALUES(NULL,'2W','Welcome Air');
INSERT INTO airlines VALUES(NULL,'KA','Cathay Dragon');
INSERT INTO airlines VALUES(NULL,'4U','Germanwings');
INSERT INTO airlines VALUES(NULL,'2F','Afrinat International Airlines');
INSERT INTO airlines VALUES(NULL,'YU','EuroAtlantic Airways S.A.');
INSERT INTO airlines VALUES('Sriwijaya Air','SJ','Sriwijaya Air');
INSERT INTO airlines VALUES(NULL,'UF','UM Airlines');
INSERT INTO airlines VALUES(NULL,'3M','Silver Airways');
INSERT INTO airlines VALUES(NULL,'K2','Eurolot');
INSERT INTO airlines VALUES(NULL,'NC','Cobham Aviation Services Australia');
INSERT INTO airlines VALUES(NULL,'ZU','SUN-AIR');
INSERT INTO airlines VALUES(NULL,'BR','Eva Air');
INSERT INTO airlines VALUES(NULL,'01','JetHunter');
INSERT INTO airlines VALUES(NULL,'8B','Business Air Co Ltd');
INSERT INTO airlines VALUES(NULL,'HQ','Thomas Cook Airlines Belgium');
INSERT INTO airlines VALUES(NULL,'9I','Alliance Air');
INSERT INTO airlines VALUES(NULL,'1V','Galileo International');
INSERT INTO airlines VALUES(NULL,'WP','Island Air');
INSERT INTO airlines VALUES(NULL,'FA','Safair');
INSERT INTO airlines VALUES(NULL,'M4','Mistral Air');
INSERT INTO airlines VALUES(NULL,'DX','Danish Air Transport');
INSERT INTO airlines VALUES(NULL,'PD','Porter Airlines');
INSERT INTO airlines VALUES(NULL,'OJ','Fly Jamaica Airways');
INSERT INTO airlines VALUES(NULL,'TL','Airnorth');
INSERT INTO airlines VALUES(NULL,'1E','Travelsky Technology Limited');
INSERT INTO airlines VALUES(NULL,'R3','Yakutia Airlines');
INSERT INTO airlines VALUES(NULL,'Q6','Skytrans Airlines');
INSERT INTO airlines VALUES(NULL,'UD','Hex Air');
INSERT INTO airlines VALUES(NULL,'U7','Air Uganda');
INSERT INTO airlines VALUES(NULL,'6H','Israir Airlines');
INSERT INTO airlines VALUES(NULL,'EW','Eurowings');
INSERT INTO airlines VALUES(NULL,'TO','Transavia');
INSERT INTO airlines VALUES(NULL,'U6','Ural Airlines');
INSERT INTO airlines VALUES(NULL,'Y5','Golden Myanmar Airlines Public Co., Ltd');
INSERT INTO airlines VALUES(NULL,'SN','Brussels Airlines');
INSERT INTO airlines VALUES(NULL,'E5','Air Arabia Egypt');
INSERT INTO airlines VALUES(NULL,'6J','Solaseed Air');
INSERT INTO airlines VALUES(NULL,'N9','Nova Airways');
INSERT INTO airlines VALUES(NULL,'PRM','Premier Airlines');
INSERT INTO airlines VALUES(NULL,'EQ','TAME Linea Aerea del Ecuador');
INSERT INTO airlines VALUES(NULL,'WF','Wideroe');
INSERT INTO airlines VALUES(NULL,'PA','airblue');
INSERT INTO airlines VALUES(NULL,'0B','Blue Air');
INSERT INTO airlines VALUES(NULL,'T8','Telair International GmbH');
INSERT INTO airlines VALUES(NULL,'UH','Atlasjet Ukraine');
INSERT INTO airlines VALUES(NULL,'OA','Olympic Air');
INSERT INTO airlines VALUES(NULL,'BU','Compagnie Africaine d''Aviation');
INSERT INTO airlines VALUES(NULL,'YK','Avia Traffic Company');
INSERT INTO airlines VALUES(NULL,'FE','Far Eastern Air Transport');
INSERT INTO airlines VALUES(NULL,'BT','airBaltic');
INSERT INTO airlines VALUES(NULL,'SL','Thai Lion Air');
INSERT INTO airlines VALUES(NULL,'MJ','MyWay Airlines');
INSERT INTO airlines VALUES(NULL,'8S','TurboJET');
INSERT INTO airlines VALUES(NULL,'6W','FlyBosnia');
INSERT INTO airlines VALUES(NULL,'5E','Siam Ga Co. Ltd.');
INSERT INTO airlines VALUES(NULL,'K5','SeaPort Airlines');
INSERT INTO airlines VALUES(NULL,'UA','United Airlines');
INSERT INTO airlines VALUES(NULL,'GG','Sky Lease I, Inc.');
INSERT INTO airlines VALUES(NULL,'RJ','Royal Jordanian');
INSERT INTO airlines VALUES(NULL,'QB','Qeshm Air');
INSERT INTO airlines VALUES(NULL,'QQ','Alliance Airlines');
INSERT INTO airlines VALUES(NULL,'3L','Air Arabia Abu Dhabi');
INSERT INTO airlines VALUES(NULL,'CH','Bemidji Airlines');
INSERT INTO airlines VALUES(NULL,'MT','Thomas Cook Airlines');
INSERT INTO airlines VALUES(NULL,'XH','Special Ground Handling Service -XH');
INSERT INTO airlines VALUES(NULL,'EU','Chengdu Airlines');
INSERT INTO airlines VALUES(NULL,'J9','Jazeera Airways');
INSERT INTO airlines VALUES(NULL,'FU','Fuzhou Airlines');
INSERT INTO airlines VALUES(NULL,'U1','Videcom International Limited');
INSERT INTO airlines VALUES(NULL,'JA','B&H Airlines');
INSERT INTO airlines VALUES(NULL,'NB','Skypower Express Airways');
INSERT INTO airlines VALUES(NULL,'ZC','Korongo Airlines');
INSERT INTO airlines VALUES(NULL,'7V','Federal Air');
INSERT INTO airlines VALUES(NULL,'7S','Ryan Air Service');
INSERT INTO airlines VALUES(NULL,'1T','PT Aerosystems Indonesia');
INSERT INTO airlines VALUES(NULL,'5J','Cebu Pacific');
INSERT INTO airlines VALUES(NULL,'UE','Ultimate Jetcharters');
INSERT INTO airlines VALUES(NULL,'PO','Polar Air Cargo Worldwide, Inc.');
INSERT INTO airlines VALUES(NULL,'XL','LATAM Ecuador');
INSERT INTO airlines VALUES(NULL,'A2','Animawings');
INSERT INTO airlines VALUES(NULL,'WB','RwandAir');
INSERT INTO airlines VALUES(NULL,'B8','Eritrean Airlines');
INSERT INTO airlines VALUES(NULL,'2S','Kinda Airlines');
INSERT INTO airlines VALUES(NULL,'LD','AHK Air Hong Kong Limited');
INSERT INTO airlines VALUES(NULL,'P0','Proflight Zambia');
INSERT INTO airlines VALUES(NULL,'KN','China United Airlines');
INSERT INTO airlines VALUES(NULL,'PC','Pegasus Airlines');
INSERT INTO airlines VALUES(NULL,'C8','Cronos Airlines');
INSERT INTO airlines VALUES(NULL,'KV','Asian Express Airline');
INSERT INTO airlines VALUES(NULL,'PV','St Barth Commuter');
INSERT INTO airlines VALUES(NULL,'YE','Yan Air Ltd');
INSERT INTO airlines VALUES(NULL,'ZX','Air Georgian Ltd. dba Air Alliance');
INSERT INTO airlines VALUES(NULL,'S3','Santa Barbara Airlines');
INSERT INTO airlines VALUES(NULL,'V9','Thai Vietjet Air');
INSERT INTO airlines VALUES(NULL,'LL','Miami Air International');
INSERT INTO airlines VALUES(NULL,'CG','Airlines PNG');
INSERT INTO airlines VALUES(NULL,'T3','Eastern Airways');
INSERT INTO airlines VALUES(NULL,'WT','Swiftair');
INSERT INTO airlines VALUES(NULL,'AD','Azul Brazilian Airlines');
INSERT INTO airlines VALUES(NULL,'4I','IHY Izmir Havayollari A.S.');
INSERT INTO airlines VALUES(NULL,'D7','AirAsia X');
INSERT INTO airlines VALUES(NULL,'QK','Jazz');
INSERT INTO airlines VALUES(NULL,'YS','HOP!');
INSERT INTO airlines VALUES(NULL,'ML','Air Mediterranee');
INSERT INTO airlines VALUES(NULL,'SI','Blue Islands');
INSERT INTO airlines VALUES(NULL,'DQ','Delta Connection');
INSERT INTO airlines VALUES(NULL,'BZ','Blue Bird Airways');
INSERT INTO airlines VALUES(NULL,'XZ','South African Express');
INSERT INTO airlines VALUES(NULL,'XA','ARINC(Aeronautical Radio, Inc.)');
INSERT INTO airlines VALUES(NULL,'PL','Southern Air Charter');
INSERT INTO airlines VALUES(NULL,'UZ','Buraq Air Transport (BRQ)');
INSERT INTO airlines VALUES(NULL,'JP','Adria Airways');
INSERT INTO airlines VALUES(NULL,'X4','Air Excursion, LLC');
INSERT INTO airlines VALUES(NULL,'UX','Air Europa');
INSERT INTO airlines VALUES(NULL,'KR','Air Bishkek');
INSERT INTO airlines VALUES(NULL,'T7','Twin Jet');
INSERT INTO airlines VALUES(NULL,'QD','Dobrolet');
INSERT INTO airlines VALUES(NULL,'RZ','Sansa Airlines');
INSERT INTO airlines VALUES(NULL,'S6','Sunrise Airways');
INSERT INTO airlines VALUES(NULL,'CT','Alitalia CityLiner');
INSERT INTO airlines VALUES(NULL,'SM','AIR CAIRO');
INSERT INTO airlines VALUES(NULL,'AB','Air Berlin');
INSERT INTO airlines VALUES(NULL,'PX','Air Niugini');
INSERT INTO airlines VALUES(NULL,'9R','Southern Air');
INSERT INTO airlines VALUES(NULL,'E2','Eagle Atlantic Airlines');
INSERT INTO airlines VALUES(NULL,'A5','HOP!');
INSERT INTO airlines VALUES(NULL,'PM','Canaryfly');
INSERT INTO airlines VALUES(NULL,'9A','Eaglexpress Air Charter Sdn.Bhd.dbaEaglexpress Air');
INSERT INTO airlines VALUES(NULL,'SA','South African Airways');
INSERT INTO airlines VALUES(NULL,'9S','Southern Air Inc.');
INSERT INTO airlines VALUES(NULL,'RI','Tigerair Mandala');
INSERT INTO airlines VALUES(NULL,'NM','Manx2');
INSERT INTO airlines VALUES(NULL,'YN','Air Creebec');
INSERT INTO airlines VALUES(NULL,'VE','C.A.I. Second');
INSERT INTO airlines VALUES(NULL,'7W','Windrose Airlines');
INSERT INTO airlines VALUES(NULL,'NK','Spirit Airlines');
INSERT INTO airlines VALUES(NULL,'8C','Air Transport International L.L.C.');
INSERT INTO airlines VALUES(NULL,'B7','Uni Air');
INSERT INTO airlines VALUES(NULL,'ED','AirExplore');
INSERT INTO airlines VALUES(NULL,'1C','Hewlett-Packard (Schweiz) GmbH');
INSERT INTO airlines VALUES(NULL,'DB','Brit Air');
INSERT INTO airlines VALUES(NULL,'1U','ITA Software Inc.');
INSERT INTO airlines VALUES(NULL,'B5','East African Safari Air');
INSERT INTO airlines VALUES(NULL,'HN','Afghan Jet International');
INSERT INTO airlines VALUES(NULL,'CK','China Cargo Airlines');
INSERT INTO airlines VALUES(NULL,'XO','South East Asian Airlines (SEAIR)International, Inc.');
INSERT INTO airlines VALUES(NULL,'SE','XL Airways France');
INSERT INTO airlines VALUES(NULL,'3V','TNT Airways');
INSERT INTO airlines VALUES(NULL,'J0','Jetlink Express');
INSERT INTO airlines VALUES(NULL,'0Q','Hydro - Quebec');
INSERT INTO airlines VALUES(NULL,'8Q','Onur Air');
INSERT INTO airlines VALUES(NULL,'JN','Joon');
INSERT INTO airlines VALUES(NULL,'GP','Guangxi Beibu Gulf Airlines Co., Ltd.');
INSERT INTO airlines VALUES(NULL,'Q2','Maldivian');
INSERT INTO airlines VALUES(NULL,'W6','Wizz Air');
INSERT INTO airlines VALUES(NULL,'R7','Aserca Airlines');
INSERT INTO airlines VALUES(NULL,'8V','Wright Air Service');
INSERT INTO airlines VALUES(NULL,'0H','Uzbekistan Airways Express');
INSERT INTO airlines VALUES(NULL,'ZF','Azur Air');
INSERT INTO airlines VALUES(NULL,'TE','Sky-Taxi');
INSERT INTO airlines VALUES(NULL,'D2','Severstal Air');
INSERT INTO airlines VALUES(NULL,'AM','Aeromexico');
INSERT INTO airlines VALUES(NULL,'U9','Tatarstan Airlines');
INSERT INTO airlines VALUES(NULL,'ST','Germania');
INSERT INTO airlines VALUES(NULL,'H9','Himalaya Airlines');
INSERT INTO airlines VALUES(NULL,'OV','SalamAir');
INSERT INTO airlines VALUES(NULL,'7O','Travel Service');
INSERT INTO airlines VALUES(NULL,'TG','Thai Airways');
INSERT INTO airlines VALUES(NULL,'MC','Air Mobility Command');
INSERT INTO airlines VALUES(NULL,'LZ','Belle Air');
INSERT INTO airlines VALUES(NULL,'Z3','PM Air LLC');
INSERT INTO airlines VALUES(NULL,'V8','Iliamna Air Taxi Inc.');
INSERT INTO airlines VALUES(NULL,'IZ','Arkia');
INSERT INTO airlines VALUES(NULL,'XB','IATA - Clearing HouseInternational Air Transport Association');
INSERT INTO airlines VALUES(NULL,'1F','INFINI Travel Information, Inc.');
INSERT INTO airlines VALUES(NULL,'7B','Bees Airline');
INSERT INTO airlines VALUES(NULL,'1N','Navitaire');
INSERT INTO airlines VALUES(NULL,'PF','Primera Air');
INSERT INTO airlines VALUES(NULL,'R1','Zapways, Inc.');
INSERT INTO airlines VALUES(NULL,'N2','Trans-Mediterranean Airways');
INSERT INTO airlines VALUES(NULL,'BI','Royal Brunei');
INSERT INTO airlines VALUES(NULL,'MF','Xiamen Airlines');
INSERT INTO airlines VALUES(NULL,'3O','Air Arabia Maroc');
INSERT INTO airlines VALUES(NULL,'F8','Flair Airlines Ltd.');
INSERT INTO airlines VALUES(NULL,'LC','Skyway Costa Rica');
INSERT INTO airlines VALUES(NULL,'8W','Private Wings');
INSERT INTO airlines VALUES(NULL,'8K','K-Mile Air Co. Ltd');
INSERT INTO airlines VALUES(NULL,'JZ','Jatayu Airlines');
INSERT INTO airlines VALUES(NULL,'I8','Izhavia');
INSERT INTO airlines VALUES(NULL,'IO','IrAero');
INSERT INTO airlines VALUES(NULL,'3W','Malawian Airlines');
INSERT INTO airlines VALUES(NULL,'S2','Jet Lite');
INSERT INTO airlines VALUES(NULL,'B4','ZanAir');
INSERT INTO airlines VALUES(NULL,'VW','Aeromar');
INSERT INTO airlines VALUES(NULL,'M9','Motor Sich Airlines');
INSERT INTO airlines VALUES(NULL,'AV','Avianca');
INSERT INTO airlines VALUES(NULL,'MZ','Merpati Nusantara Airlines');
INSERT INTO airlines VALUES(NULL,'BO','BB Airways');
INSERT INTO airlines VALUES(NULL,'AG','Aruba Airlines');
INSERT INTO airlines VALUES(NULL,'LG','Luxair');
INSERT INTO airlines VALUES(NULL,'DV','SCAT');
INSERT INTO airlines VALUES(NULL,'W9','Wizz Air');
INSERT INTO airlines VALUES(NULL,'0X','Air Excel');
INSERT INTO airlines VALUES(NULL,'3P','Tiara Air Aruba');
INSERT INTO airlines VALUES(NULL,'GS','Tianjin Airlines');
INSERT INTO airlines VALUES(NULL,'UV','Helicópteros del Sureste');
INSERT INTO airlines VALUES(NULL,'9B','AccesRail');
INSERT INTO airlines VALUES(NULL,'7E','Sylt Air GmbH');
INSERT INTO airlines VALUES(NULL,'9L','West Link Airlines');
INSERT INTO airlines VALUES(NULL,'TS','Air Transat');
INSERT INTO airlines VALUES(NULL,'OK','Czech Airlines');
INSERT INTO airlines VALUES(NULL,'4B','Boutique Air');
INSERT INTO airlines VALUES(NULL,'MM','Peach');
INSERT INTO airlines VALUES(NULL,'9X','Executive Express Aviation LLC dbaSouthern Airways');
INSERT INTO airlines VALUES(NULL,'VX','Virgin America ');
INSERT INTO airlines VALUES(NULL,'TB','Jetairfly');
INSERT INTO airlines VALUES(NULL,'MW','Mokulele Airlines');
INSERT INTO airlines VALUES(NULL,'HR','Hahn Air');
INSERT INTO airlines VALUES(NULL,'NX','Air Macau');
INSERT INTO airlines VALUES(NULL,'A7','Air Niamey');
INSERT INTO airlines VALUES(NULL,'IQ','Qazaq Air');
INSERT INTO airlines VALUES(NULL,'FJ','Fiji Airways');
INSERT INTO airlines VALUES(NULL,'AA','American Airlines');
INSERT INTO airlines VALUES(NULL,'5R','Rutas Aereas, C.A. dba  RUTACA');
INSERT INTO airlines VALUES(NULL,'HS','Héli Sécurité Hélicopter Airline');
INSERT INTO airlines VALUES(NULL,'HD','Air Do');
INSERT INTO airlines VALUES(NULL,'CE','Chalair Aviation');
INSERT INTO airlines VALUES(NULL,'B3','Bhutan Airlines');
INSERT INTO airlines VALUES(NULL,'J4','BADR AIRLINES');
INSERT INTO airlines VALUES(NULL,'D0','DHL Air Limited');
INSERT INTO airlines VALUES(NULL,'NL','Shaheen Air');
INSERT INTO airlines VALUES(NULL,'DY','Norwegian Air Shuttle');
INSERT INTO airlines VALUES(NULL,'GZ','Air Rarotonga');
INSERT INTO airlines VALUES(NULL,'ON','Nauru Airline');
INSERT INTO airlines VALUES(NULL,'YR','Grand Canyon Airlines, Inc.dba Scenic Airlines');
INSERT INTO airlines VALUES(NULL,'KY','Kunming Airlines');
INSERT INTO airlines VALUES(NULL,'KF','Blue1');
INSERT INTO airlines VALUES(NULL,'Z9','Bek Air');
INSERT INTO airlines VALUES(NULL,'TU','Tunisair');
INSERT INTO airlines VALUES(NULL,'S1','Lufthansa Systems');
INSERT INTO airlines VALUES(NULL,'IW','Wings Air');
INSERT INTO airlines VALUES(NULL,'XV','BVI Airways');
INSERT INTO airlines VALUES(NULL,'4L','Palau National Airlines');
INSERT INTO airlines VALUES(NULL,'OB','Boliviana de Aviación');
INSERT INTO airlines VALUES(NULL,'DJ','AirAsia Japan');
INSERT INTO airlines VALUES(NULL,'TT','Tigerair Australia');
INSERT INTO airlines VALUES(NULL,'N8','National Airlines');
INSERT INTO airlines VALUES(NULL,'T0','TACA Peru');
INSERT INTO airlines VALUES(NULL,'Z8','Amaszonas');
INSERT INTO airlines VALUES(NULL,'QL','LASER Airlines');
INSERT INTO airlines VALUES(NULL,'7A','Air Jet');
INSERT INTO airlines VALUES(NULL,'0J','Premium Jet AG');
INSERT INTO airlines VALUES(NULL,'HF','Air Côte d''Ivoire');
INSERT INTO airlines VALUES(NULL,'NF','Air Vanuatu');
INSERT INTO airlines VALUES(NULL,'TV','Tibet Airlines');
INSERT INTO airlines VALUES(NULL,'FC','FlyCorporate');
INSERT INTO airlines VALUES(NULL,'LX','Swiss International Air Lines');
INSERT INTO airlines VALUES(NULL,'ZY','Sky Airlines');
INSERT INTO airlines VALUES(NULL,'TX','Air Caraibes');
INSERT INTO airlines VALUES(NULL,'4O','Interjet');
INSERT INTO airlines VALUES(NULL,'DU','Norwegian Long Haul');
INSERT INTO airlines VALUES(NULL,'LS','Jet2.com');
INSERT INTO airlines VALUES(NULL,'FG','Ariana Afghan Airlines');
INSERT INTO airlines VALUES(NULL,'NT','Binter Canarias');
INSERT INTO airlines VALUES(NULL,'LE','Laparkan Airways, Inc.');
INSERT INTO airlines VALUES(NULL,'LN','Libyan Airlines');
INSERT INTO airlines VALUES(NULL,'5V','Everts Air Cargo');
INSERT INTO airlines VALUES(NULL,'2Y','PT. My Indo Airlines');
INSERT INTO airlines VALUES(NULL,'W5','Mahan Airlines');
INSERT INTO airlines VALUES(NULL,'WO','Swoop');
INSERT INTO airlines VALUES(NULL,'2J','Air Burkina');
INSERT INTO airlines VALUES(NULL,'O2','Linear Air');
INSERT INTO airlines VALUES(NULL,'4G','Gazpromavia');
INSERT INTO airlines VALUES(NULL,'C4','Conquest Air, Inc.');
INSERT INTO airlines VALUES(NULL,'SZ','Somon Air');
INSERT INTO airlines VALUES(NULL,'6L','Aklak Air');
INSERT INTO airlines VALUES(NULL,'Q9','Air Liaison');
INSERT INTO airlines VALUES(NULL,'JF','Jet Asia Airways');
INSERT INTO airlines VALUES(NULL,'AX','Trans States Airlines');
INSERT INTO airlines VALUES(NULL,'G9','Air Arabia');
INSERT INTO airlines VALUES(NULL,'JT','Lion Air');
INSERT INTO airlines VALUES(NULL,'VT','Air Tahiti');
INSERT INTO airlines VALUES(NULL,'OM','MIAT Mongolian Airlines');
INSERT INTO airlines VALUES(NULL,'QJ','Jet Airways Inc.');
INSERT INTO airlines VALUES(NULL,'OZ','Asiana Airlines');
INSERT INTO airlines VALUES(NULL,'UR','Uganda Airlines');
INSERT INTO airlines VALUES(NULL,'8N','Regional Air Services');
INSERT INTO airlines VALUES(NULL,'VQ','Novoair');
INSERT INTO airlines VALUES(NULL,'VV','Viva Air');
INSERT INTO airlines VALUES(NULL,'3U','Sichuan Airlines');
INSERT INTO airlines VALUES(NULL,'6R','Alrosa');
INSERT INTO airlines VALUES('Regional Jet OÜ','EE','Regional Jet OÜ');
INSERT INTO airlines VALUES(NULL,'T2','Nakina Air Service');
INSERT INTO airlines VALUES(NULL,'XY','Nas Air');
INSERT INTO airlines VALUES(NULL,'DW','Aero-Charter Ukraine');
INSERT INTO airlines VALUES(NULL,'0E','Emetebe S.A.');
INSERT INTO airlines VALUES(NULL,'RC','Atlantic Airways');
INSERT INTO airlines VALUES(NULL,'1P','Worldspan');
INSERT INTO airlines VALUES(NULL,'PN','China West Air');
INSERT INTO airlines VALUES(NULL,'NE','Nesma Airlines');
INSERT INTO airlines VALUES(NULL,'O4','Antrak Air');
INSERT INTO airlines VALUES(NULL,'Z6','Dniproavia');
INSERT INTO airlines VALUES(NULL,'NW','Northwest Airlines');
INSERT INTO airlines VALUES(NULL,'JC','Japan Air Commuter');
INSERT INTO airlines VALUES(NULL,'KQ','Kenya Airways');
INSERT INTO airlines VALUES(NULL,'RK','Skyview Airways Company Limiteddba Skyview');
INSERT INTO airlines VALUES(NULL,'QZ','Indonesia AirAsia');
INSERT INTO airlines VALUES(NULL,'N4','Nordwind Airlines');
INSERT INTO airlines VALUES(NULL,'KD','PT Kal Star Aviation');
INSERT INTO airlines VALUES(NULL,'DC','Braathens Regional');
INSERT INTO airlines VALUES(NULL,'EG','Ernest Airline');
INSERT INTO airlines VALUES(NULL,'TN','Air Tahiti Nui');
INSERT INTO airlines VALUES(NULL,'WU','Wizz Air Ukraine');
INSERT INTO airlines VALUES(NULL,'PR','Philippine Airlines');
INSERT INTO airlines VALUES('Vistara','UK','Vistara');
INSERT INTO airlines VALUES(NULL,'EB','Wamos Air');
INSERT INTO airlines VALUES('Business jet','0W','Business jet');
INSERT INTO airlines VALUES(NULL,'WK','Edelweiss Air');
INSERT INTO airlines VALUES(NULL,'UJ','Almasria Universal Airlines');
INSERT INTO airlines VALUES(NULL,'AE','Mandarin Airlines');
INSERT INTO airlines VALUES(NULL,'JB','Helijet');
INSERT INTO airlines VALUES(NULL,'FX','FedEx');
INSERT INTO airlines VALUES(NULL,'PW','Precision Air');
INSERT INTO airlines VALUES(NULL,'3T','Tarco Air');
INSERT INTO airlines VALUES(NULL,'C1','Tectimes Sudamerica');
INSERT INTO airlines VALUES(NULL,'L9','Lumiwings');
INSERT INTO airlines VALUES(NULL,'YX','Republic Airlines');
INSERT INTO airlines VALUES(NULL,'NU','Japan Transocean Air');
INSERT INTO airlines VALUES(NULL,'KP','ASKY Airlines');
INSERT INTO airlines VALUES(NULL,'6U','Air Cargo Germany');
INSERT INTO airlines VALUES(NULL,'KX','Cayman Airways');
INSERT INTO airlines VALUES(NULL,'CD','Corendon Dutch Airlines');
INSERT INTO airlines VALUES(NULL,'CZ','China Southern Airlines');
INSERT INTO airlines VALUES(NULL,'2L','Helvetic Airways');
INSERT INTO airlines VALUES(NULL,'KI','KrasAvia');
INSERT INTO airlines VALUES(NULL,'3K','Jetstar Asia');
INSERT INTO airlines VALUES(NULL,'F3','Flyadeal');
INSERT INTO airlines VALUES(NULL,'I9','Air Italy');
INSERT INTO airlines VALUES(NULL,'LV','Level');
INSERT INTO airlines VALUES(NULL,'3D','DoKaSch');
INSERT INTO airlines VALUES(NULL,'BH','Hawkair');
INSERT INTO airlines VALUES(NULL,'1S','Sabre Inc.');
INSERT INTO airlines VALUES(NULL,'9G','9G Rail');
INSERT INTO airlines VALUES(NULL,'LA','LATAM Chile');
INSERT INTO airlines VALUES(NULL,'UI','Auric Air Services Limited');
INSERT INTO airlines VALUES(NULL,'FR','Ryanair');
INSERT INTO airlines VALUES(NULL,'IU','SW Italia s.p.a.');
INSERT INTO airlines VALUES(NULL,'SU','Aeroflot');
INSERT INTO airlines VALUES(NULL,'XI','Aeronautical Telecommunications Ltd.(AEROTEL)');
INSERT INTO airlines VALUES(NULL,'F9','Frontier Airlines');
INSERT INTO airlines VALUES(NULL,'R5','Jordan Aviation');
INSERT INTO airlines VALUES(NULL,'4A','Aero Transporte S.A.');
INSERT INTO airlines VALUES(NULL,'JI','Meraj Air');
INSERT INTO airlines VALUES(NULL,'6V','AVANZA');
INSERT INTO airlines VALUES(NULL,'YC','Yamal Airlines');
INSERT INTO airlines VALUES(NULL,'XE','ExpressJet');
INSERT INTO airlines VALUES(NULL,'FO','Felix Airways');
INSERT INTO airlines VALUES(NULL,'1J','Axess International Network Inc.');
INSERT INTO airlines VALUES(NULL,'AT','Royal Air Maroc');
INSERT INTO airlines VALUES(NULL,'ZG','ZIPAIR Tokyo');
INSERT INTO airlines VALUES(NULL,'EN','Air Dolomiti');
INSERT INTO airlines VALUES(NULL,'R4','RUS Aviation');
INSERT INTO airlines VALUES(NULL,'QA','Cimber');
INSERT INTO airlines VALUES(NULL,'YV','Mesa Airlines');
INSERT INTO airlines VALUES(NULL,'4Y','Airbus Transport International');
INSERT INTO airlines VALUES(NULL,'XX','Major Airline');
INSERT INTO airlines VALUES(NULL,'X5','S.C. Ten Airways S.R.L.');
INSERT INTO airlines VALUES(NULL,'XM','C.A.I. First');
INSERT INTO airlines VALUES(NULL,'Q8','Trans Air Congo');
INSERT INTO airlines VALUES(NULL,'T5','Turkmenistan Airlines');
INSERT INTO airlines VALUES(NULL,'D9','Donavia');
INSERT INTO airlines VALUES(NULL,'IK','Air Kiribati Limited');
INSERT INTO airlines VALUES(NULL,'S9','Starbow');
INSERT INTO airlines VALUES(NULL,'1K','Sutra Inc.');
INSERT INTO airlines VALUES(NULL,'ZP','Silk Way Airlines');
INSERT INTO airlines VALUES(NULL,'R0','Russian Railways');
INSERT INTO airlines VALUES(NULL,'7H','Ravn Alaska');
INSERT INTO airlines VALUES(NULL,'TK','Turkish Airlines');
INSERT INTO airlines VALUES(NULL,'7L','Aerocaribbean');
INSERT INTO airlines VALUES(NULL,'OC','Oriental Air Bridge');
INSERT INTO airlines VALUES(NULL,'V3','Carpatair');
INSERT INTO airlines VALUES(NULL,'LI','Liat');
INSERT INTO airlines VALUES(NULL,'F1','Farelogix Qatar Airways');
INSERT INTO airlines VALUES(NULL,'O8','Siam Air');
INSERT INTO airlines VALUES(NULL,'V5','Aerovías DAP');
INSERT INTO airlines VALUES(NULL,'ZE','Eastar Jet');
INSERT INTO airlines VALUES(NULL,'2M','Moldavian Airlines');
INSERT INTO airlines VALUES(NULL,'I4','Interstate Airlines');
INSERT INTO airlines VALUES(NULL,'TH','Raya Airways Sdn. Bhd.dba Raya Airways');
INSERT INTO airlines VALUES(NULL,'IH','Southern Sky');
INSERT INTO airlines VALUES(NULL,'Y1','Travel Technology Interactive SA');
INSERT INTO airlines VALUES(NULL,'GR','Aurigny Air Services');
INSERT INTO airlines VALUES(NULL,'RR','Buzz');
INSERT INTO airlines VALUES(NULL,'S4','SATA');
INSERT INTO airlines VALUES(NULL,'CQ','Coastal Travels');
INSERT INTO airlines VALUES(NULL,'J7','Afrijet Business Service');
INSERT INTO airlines VALUES(NULL,'D8','Norwegian Air International');
INSERT INTO airlines VALUES(NULL,'XS','SITA - Airlines WorldwideTelecommunications and Information Svcs');
INSERT INTO airlines VALUES(NULL,'4W','Warbelow''s Air Ventures');
INSERT INTO airlines VALUES(NULL,'DK','Thomas Cook Airlines Scandinavia');
INSERT INTO airlines VALUES(NULL,'9T','ACT Havayollari A.S.');
INSERT INTO airlines VALUES(NULL,'3F','Pacific Airways Inc.');
INSERT INTO airlines VALUES(NULL,'6C','Air Timor');
INSERT INTO airlines VALUES(NULL,'6N','Niger Airlines');
INSERT INTO airlines VALUES(NULL,'IB','Iberia');
INSERT INTO airlines VALUES(NULL,'G2','Jet Express');
INSERT INTO airlines VALUES(NULL,'ND','Sky Wings Airlines');
INSERT INTO airlines VALUES(NULL,'7N','Pan American World Airways');
INSERT INTO airlines VALUES(NULL,'2P','PAL Express');
INSERT INTO airlines VALUES(NULL,'9V','Avior Airlines');
INSERT INTO airlines VALUES(NULL,'XF','Vladivostok Air');
INSERT INTO airlines VALUES(NULL,'5D','Aerolitoral S.A. de C.V.');
INSERT INTO airlines VALUES(NULL,'V6','Clairmont Holdings Ltd dba VI Air Link');
INSERT INTO airlines VALUES(NULL,'S7','S7 Airlines');
INSERT INTO airlines VALUES(NULL,'KC','Air Astana');
INSERT INTO airlines VALUES(NULL,'OD','Malindo Air');
INSERT INTO airlines VALUES(NULL,'YI','Air Sunshine Inc.');
INSERT INTO airlines VALUES(NULL,'B9','Iran Air Tours');
INSERT INTO airlines VALUES(NULL,'XK','Air Corsica');
INSERT INTO airlines VALUES(NULL,'2V','Amtrak');
INSERT INTO airlines VALUES(NULL,'AW','Africa World Airlines');
INSERT INTO airlines VALUES(NULL,'5H','Fly540');
INSERT INTO airlines VALUES(NULL,'AS','Alaska Airlines');
INSERT INTO airlines VALUES(NULL,'WN','Southwest Airlines');
INSERT INTO airlines VALUES(NULL,'VF','Valuair');
INSERT INTO airlines VALUES(NULL,'AP','Air One');
INSERT INTO airlines VALUES(NULL,'GQ','Sky Express');
INSERT INTO airlines VALUES(NULL,'GV','Grant Aviation, Inc.');
INSERT INTO airlines VALUES(NULL,'TC','Air Tanzania');
INSERT INTO airlines VALUES(NULL,'YT','Yeti Airlines Domestic Pvt. Ltd.');
INSERT INTO airlines VALUES(NULL,'QO','Quikjet Cargo Airlines Pvt. Ltd');
INSERT INTO airlines VALUES(NULL,'GM','Germania Flug');
INSERT INTO airlines VALUES(NULL,'IX','Air India Express');
INSERT INTO airlines VALUES(NULL,'N5','Nolinor Aviation');
INSERT INTO airlines VALUES(NULL,'3C','Calima Aviacion S.L');
INSERT INTO airlines VALUES(NULL,'RP','Chautauqua Airlines');
INSERT INTO airlines VALUES(NULL,'8E','Bering Air');
INSERT INTO airlines VALUES(NULL,'SD','Sudan Airways');
INSERT INTO airlines VALUES(NULL,'4Q','Safi Airways');
INSERT INTO airlines VALUES(NULL,'PE','People''s Viennaline');
INSERT INTO airlines VALUES(NULL,'4T','Belair Airlines');
INSERT INTO airlines VALUES(NULL,'MD','Air Madagascar');
INSERT INTO airlines VALUES(NULL,'L2','Lynden Air Cargo, LLC');
INSERT INTO airlines VALUES(NULL,'WV','Westair Aviation');
INSERT INTO airlines VALUES(NULL,'EP','Iran Aseman Airlines');
INSERT INTO airlines VALUES(NULL,'LM','Loganair');
INSERT INTO airlines VALUES(NULL,'AZ','Alitalia');
INSERT INTO airlines VALUES(NULL,'4K','Kenn Borek Air Ltd.');
INSERT INTO airlines VALUES(NULL,'HP','Amapola Flyg AB');
INSERT INTO airlines VALUES(NULL,'T1','TIK Systems');
INSERT INTO airlines VALUES(NULL,'I6','Air Indus');
INSERT INTO airlines VALUES(NULL,'2Q','Air Cargo Carriers, LLC.');
INSERT INTO airlines VALUES(NULL,'FD','Thai AirAsia');
INSERT INTO airlines VALUES(NULL,'5W','Wizz Air');
INSERT INTO airlines VALUES(NULL,'W1','World Ticket Ltd');
INSERT INTO airlines VALUES(NULL,'ZL','Regional Express');
INSERT INTO airlines VALUES(NULL,'ID','Batik Air');
INSERT INTO airlines VALUES(NULL,'G3','Gol Transportes Aéreos');
INSERT INTO airlines VALUES(NULL,'NG','Aero Contractors');
INSERT INTO airlines VALUES(NULL,'SG','SpiceJet');
INSERT INTO airlines VALUES(NULL,'UB','Myanmar National Airlines');
INSERT INTO airlines VALUES(NULL,'MQ','Envoy Air');
INSERT INTO airlines VALUES(NULL,'KH','Kyrgyz Air');
INSERT INTO airlines VALUES(NULL,'SY','Sun Country Airlines');
INSERT INTO airlines VALUES(NULL,'7Z','Halcyonair');
INSERT INTO airlines VALUES(NULL,'BN','Bahrain Air');
INSERT INTO airlines VALUES(NULL,'RF','Connellan air disaster');
INSERT INTO airlines VALUES(NULL,'JW','Vanilla Air');
INSERT INTO airlines VALUES(NULL,'2C','SNCF');
INSERT INTO airlines VALUES(NULL,'YW','Air Nostrum');
INSERT INTO airlines VALUES(NULL,'EC','OpenSkies');
INSERT INTO airlines VALUES(NULL,'YQ','Polet Airlines');
INSERT INTO airlines VALUES(NULL,'IM','JSC Aircompany ATMA');
INSERT INTO airlines VALUES(NULL,'PK','Pakistan International Airlines');
INSERT INTO airlines VALUES(NULL,'J2','Azerbaijan Airlines');
INSERT INTO airlines VALUES(NULL,'YG','South Airlines');
INSERT INTO airlines VALUES(NULL,'N3','Aerolíneas Mas');
INSERT INTO airlines VALUES(NULL,'LB','Bul Air');
INSERT INTO airlines VALUES(NULL,'RO','Tarom');
INSERT INTO airlines VALUES(NULL,'VO','Tyrolean Airways');
INSERT INTO airlines VALUES(NULL,'FY','Firefly');
INSERT INTO airlines VALUES(NULL,'V7','Volotea');
INSERT INTO airlines VALUES(NULL,'DP','Pobeda');
INSERT INTO airlines VALUES(NULL,'F7','iFly Airlines');
INSERT INTO airlines VALUES(NULL,'U8','Tus Airways');
INSERT INTO airlines VALUES(NULL,'KB','Druk Air');
INSERT INTO airlines VALUES(NULL,'5B','Bassaka Air Limited');
INSERT INTO airlines VALUES(NULL,'BW','Caribbean Airlines');
INSERT INTO airlines VALUES(NULL,'JE','Mango');
INSERT INTO airlines VALUES(NULL,'J3','Northwestern Air');
INSERT INTO airlines VALUES(NULL,'ZS','JSC Kazaviaspas');
INSERT INTO airlines VALUES(NULL,'LY','El Al Israel Airlines');
INSERT INTO airlines VALUES(NULL,'KW','Kharkiv Airlines');
INSERT INTO airlines VALUES(NULL,'4M','LATAM Argentina');
INSERT INTO airlines VALUES(NULL,'FN','fastjet');
INSERT INTO airlines VALUES(NULL,'SX','SkyWork Airlines');
INSERT INTO airlines VALUES(NULL,'3G','Gambia Bird Airlines');
INSERT INTO airlines VALUES(NULL,'4F','Air City');
INSERT INTO airlines VALUES(NULL,'IJ','Spring Airlines Japan');
INSERT INTO airlines VALUES(NULL,'K7','Air KBZ');
INSERT INTO airlines VALUES(NULL,'QT','Avianca Cargo');
INSERT INTO airlines VALUES(NULL,'S8','Sounds Air Travel & Tourism Ltd.');
INSERT INTO airlines VALUES(NULL,'KT','SiAvia');
INSERT INTO airlines VALUES(NULL,'DM','Asian Air');
INSERT INTO airlines VALUES(NULL,'SW','Air Namibia');
INSERT INTO airlines VALUES(NULL,'7I','Insel Air');
INSERT INTO airlines VALUES(NULL,'7U','Alpha Air Transport');
INSERT INTO airlines VALUES(NULL,'1D','Radixx Solutions International, Inc.');
INSERT INTO airlines VALUES(NULL,'IG','Air Italy');
INSERT INTO airlines VALUES(NULL,'ZT','Titan Airways Limited');
INSERT INTO airlines VALUES(NULL,'ZV','V Air Corporation');
INSERT INTO airlines VALUES(NULL,'CI','China Airlines');
INSERT INTO airlines VALUES(NULL,'UM','Air Zimbabwe');
INSERT INTO airlines VALUES(NULL,'DZ','Donghai Airlines');
INSERT INTO airlines VALUES(NULL,'QV','Lao Airlines');
INSERT INTO airlines VALUES(NULL,'QC','Camair-Co');
INSERT INTO airlines VALUES(NULL,'YJ','Asian Wings Airways Limited');
INSERT INTO airlines VALUES(NULL,'X7','Exec Air, Inc. of Naples');
INSERT INTO airlines VALUES(NULL,'BP','Air Botswana');
INSERT INTO airlines VALUES(NULL,'ZM','Air Manas');
INSERT INTO airlines VALUES(NULL,'ZK','Great Lakes Airlines');
INSERT INTO airlines VALUES(NULL,'H4','HiSky');
INSERT INTO airlines VALUES(NULL,'DO','Discovery Airways');
INSERT INTO airlines VALUES(NULL,'G6','Ghadames Air Transport');
INSERT INTO airlines VALUES(NULL,'EM','Empire Airlines');
INSERT INTO airlines VALUES(NULL,'VH','Aeropostal Alas de Venezuela');
INSERT INTO airlines VALUES(NULL,'UY','Air Caucasus');
INSERT INTO airlines VALUES(NULL,'2N','Nextjet');
INSERT INTO airlines VALUES(NULL,'4P','Travel Air');
INSERT INTO airlines VALUES(NULL,'CF','China Postal Airlines Ltd.');
INSERT INTO airlines VALUES(NULL,'7J','Tajik Air');
INSERT INTO airlines VALUES(NULL,'YF','Department of National Defence');
INSERT INTO airlines VALUES(NULL,'QU','Azur Air Ukraine');
INSERT INTO airlines VALUES(NULL,'WI','White Airways');
INSERT INTO airlines VALUES(NULL,'IS','AIS Airlines B.V.');
INSERT INTO airlines VALUES(NULL,'KG','Aerogaviota');
INSERT INTO airlines VALUES(NULL,'CM','Copa Airlines');
INSERT INTO airlines VALUES(NULL,'M2','MHS Aviation');
INSERT INTO airlines VALUES(NULL,'D4','Alidaunia');
INSERT INTO airlines VALUES(NULL,'C5','CommutAir');
INSERT INTO airlines VALUES(NULL,'7M','MAYAir');
INSERT INTO airlines VALUES(NULL,'2B','Ak Bars Aero');
INSERT INTO airlines VALUES(NULL,'NZ','Air New Zealand');
INSERT INTO airlines VALUES(NULL,'G8','Go!');
INSERT INTO airlines VALUES(NULL,'I3','ATA Airlines');
INSERT INTO airlines VALUES(NULL,'A3','Aegean Airlines');
INSERT INTO airlines VALUES(NULL,'PH','Transavia Denmark');
INSERT INTO airlines VALUES(NULL,'5M','Hi Fly Ltd');
INSERT INTO airlines VALUES(NULL,'P7','Small Planet Airlines');
INSERT INTO airlines VALUES(NULL,'TM','LAM Mozambique Airlines');
INSERT INTO airlines VALUES(NULL,'WE','Thai Smile');
INSERT INTO airlines VALUES(NULL,'LW','Pacific Wings');
INSERT INTO airlines VALUES(NULL,'FV','Rossiya Airlines');
INSERT INTO airlines VALUES(NULL,'QP','Airkenya Express');
INSERT INTO airlines VALUES(NULL,'8I','Insel Air');
INSERT INTO airlines VALUES(NULL,'8G','Mid Africa Aviation');
INSERT INTO airlines VALUES(NULL,'R2','Orenair');
INSERT INTO airlines VALUES(NULL,'GI','Itek Air');
INSERT INTO airlines VALUES(NULL,'8H','BH Air');
INSERT INTO airlines VALUES(NULL,'JO','Jonika Airlines');
INSERT INTO airlines VALUES(NULL,'OT','Aeropelican Air Services');
INSERT INTO airlines VALUES(NULL,'II','IBC Airways');
INSERT INTO airlines VALUES(NULL,'BX','Air Busan');
INSERT INTO airlines VALUES(NULL,'4S','Solar Cargo, C.A.');
INSERT INTO airlines VALUES(NULL,'O9','NOVA Airlines');
INSERT INTO airlines VALUES(NULL,'JU','Air Serbia');
INSERT INTO airlines VALUES(NULL,'GB','ABX Air, Inc.');
INSERT INTO airlines VALUES(NULL,'4J','FlyDamas');
INSERT INTO airlines VALUES(NULL,'4H','Hi Air');
INSERT INTO airlines VALUES(NULL,'OX','Orient Thai Airlines');
INSERT INTO airlines VALUES(NULL,'4D','Air Sinai');
INSERT INTO airlines VALUES(NULL,'OR','TUI Airlines Netherlands');
INSERT INTO airlines VALUES(NULL,'J1','One Jet, Inc.');
INSERT INTO airlines VALUES(NULL,'E8','Tayaran Jet');
INSERT INTO airlines VALUES(NULL,'A4','Azimut');
INSERT INTO airlines VALUES(NULL,'PY','Surinam Airways');
INSERT INTO airlines VALUES(NULL,'VS','Virgin Atlantic');
INSERT INTO airlines VALUES(NULL,'P1','Public Charters');
INSERT INTO airlines VALUES(NULL,'VL','Air Via Ltd.');
INSERT INTO airlines VALUES(NULL,'J5','Alaska Seaplane');
INSERT INTO airlines VALUES(NULL,'0G','Grumeti Air');
INSERT INTO airlines VALUES(NULL,'VJ','VietjetAir');
INSERT INTO airlines VALUES(NULL,'JH','Fuji Dream Airlines');
INSERT INTO airlines VALUES(NULL,'UT','Utair');
INSERT INTO airlines VALUES(NULL,'RD','French Armed Forces');
INSERT INTO airlines VALUES(NULL,'P3','Passaredo Linhas Aereas');
INSERT INTO airlines VALUES(NULL,'NI','Portugália');
INSERT INTO airlines VALUES(NULL,'W2','FlexFlight');
INSERT INTO airlines VALUES(NULL,'RG','Rotana Jet');
INSERT INTO airlines VALUES(NULL,'OU','Croatia Airlines');
INSERT INTO airlines VALUES(NULL,'7T','Trenitalia');
INSERT INTO airlines VALUES(NULL,'DS','easyJet Switzerland');
INSERT INTO airlines VALUES(NULL,'T4','TRIP Linhas Aéreas');
INSERT INTO airlines VALUES(NULL,'PJ','Air Saint Pierre');
INSERT INTO airlines VALUES(NULL,'EV','ExpressJet');
INSERT INTO airlines VALUES(NULL,'OE','Laudamotion');
INSERT INTO airlines VALUES(NULL,'ZR','Aviacon Zitotrans Air Company JSC');
INSERT INTO airlines VALUES(NULL,'L1','E-Savtravel');
INSERT INTO airlines VALUES(NULL,'AH','Air Algerie');
INSERT INTO airlines VALUES(NULL,'PZ','LATAM Paraguay');
INSERT INTO airlines VALUES(NULL,'5G','540 Ghana Ltd.');
INSERT INTO airlines VALUES(NULL,'O6','Avianca Brazil');
INSERT INTO airlines VALUES(NULL,'EY','Etihad Airways');
INSERT INTO airlines VALUES(NULL,'KM','Air Malta');
INSERT INTO airlines VALUES('Angara Airlines','2G','Angara Airlines');
INSERT INTO airlines VALUES(NULL,'RV','8165343 Canada Inc. dba Air Canada rouge');
INSERT INTO airlines VALUES(NULL,'MG','Miami Air Lease, Inc.');
INSERT INTO airlines VALUES(NULL,'K1','Topas Co. Ltd.');
INSERT INTO airlines VALUES(NULL,'GO','ULS Airlines Cargo');
INSERT INTO airlines VALUES(NULL,'XJ','Thai AirAsia X');
INSERT INTO airlines VALUES(NULL,'BK','Okay Airways');
INSERT INTO airlines VALUES(NULL,'GY','Colorful Guizhou Airlines');
INSERT INTO airlines VALUES(NULL,'X8','Airmax S.A.');
INSERT INTO airlines VALUES(NULL,'GC','Gambia International Airlines');
INSERT INTO airlines VALUES(NULL,'9Q','Caicos Express Airways');
INSERT INTO airlines VALUES(NULL,'NQ','Air Japan');
INSERT INTO airlines VALUES(NULL,'WH','Webjet Linhas Aereas');
INSERT INTO airlines VALUES(NULL,'L3','Lynx Aviation');
INSERT INTO airlines VALUES(NULL,'H1','Hahn Air');
INSERT INTO airlines VALUES(NULL,'6A','Armenia Airways');
INSERT INTO airlines VALUES(NULL,'P2','Airkenya Express');
INSERT INTO airlines VALUES(NULL,'RH','PT Republic Express Airlines');
INSERT INTO airlines VALUES(NULL,'MN','Comair');
INSERT INTO airlines VALUES(NULL,'5U','Transportes Aéreos Regionales');
INSERT INTO airlines VALUES(NULL,'2O','Redemption Inc.');
INSERT INTO airlines VALUES(NULL,'VU','Vuelos Economicos Centroamericanos');
INSERT INTO airlines VALUES(NULL,'3Y','Kartika Airlines');
INSERT INTO airlines VALUES(NULL,'3N','Air Urga');
INSERT INTO airlines VALUES(NULL,'2E','Smokey Bay Air, Inc.');
INSERT INTO airlines VALUES(NULL,'IY','Yemenia');
INSERT INTO airlines VALUES(NULL,'H2','Sky Airline');
INSERT INTO airlines VALUES(NULL,'ZW','Air Wisconsin Airlines Corporation(AWAC)');
INSERT INTO airlines VALUES(NULL,'8L','Lucky Air');
INSERT INTO airlines VALUES(NULL,'YH','Sunsplash Aviation, LLC.');
INSERT INTO airlines VALUES(NULL,'BE','Flybe');
INSERT INTO airlines VALUES(NULL,'Q3','Anguilla Air Services, Ltd');
INSERT INTO airlines VALUES(NULL,'GH','Globus Airlines');
INSERT INTO airlines VALUES(NULL,'FI','Icelandair');
INSERT INTO airlines VALUES(NULL,'3X','Premier Trans Aire Inc.');
INSERT INTO airlines VALUES(NULL,'UU','Air Austral');
INSERT INTO airlines VALUES(NULL,'G4','Allegiant Air');
INSERT INTO airlines VALUES(NULL,'9K','Cape Air');
INSERT INTO airlines VALUES(NULL,'9J','Dana Airlines Limited');
INSERT INTO airlines VALUES(NULL,'CJ','BA Cityflyer');
INSERT INTO airlines VALUES(NULL,'JL','Japan Airlines');
INSERT INTO airlines VALUES(NULL,'5Z','CemAir');
INSERT INTO airlines VALUES(NULL,'1B','Abacus International Pte. Ltd.');
INSERT INTO airlines VALUES(NULL,'1Y','Electronic Data Systems Corporation');
INSERT INTO airlines VALUES(NULL,'5N','Smartavia');
INSERT INTO airlines VALUES(NULL,'RX','Regent Airways');
INSERT INTO airlines VALUES(NULL,'RQ','Kam Air');
INSERT INTO airlines VALUES(NULL,'FS','Syphax Airlines');
INSERT INTO airlines VALUES(NULL,'NO','Neos');
INSERT INTO airlines VALUES(NULL,'CB','Caribbean Air Export Import Inc.');
INSERT INTO airlines VALUES(NULL,'6E','IndiGo');
INSERT INTO airlines VALUES(NULL,'8R','Sol Lineas Aereas');
INSERT INTO airlines VALUES(NULL,'FZ','Flydubai');
INSERT INTO airlines VALUES(NULL,'ME','Middle East Airlines');
INSERT INTO airlines VALUES(NULL,'QY','European Air Transport');
INSERT INTO airlines VALUES(NULL,'2Z','Passaredo Transportes Aereos S.A.');
INSERT INTO airlines VALUES(NULL,'HV','Transavia');
INSERT INTO airlines VALUES(NULL,'LH','Lufthansa');
INSERT INTO airlines VALUES(NULL,'5C','Nature Air');
INSERT INTO airlines VALUES(NULL,'A8','Aerolink Uganda Limited');
INSERT INTO airlines VALUES(NULL,'QG','Citilink Airlines');
INSERT INTO airlines VALUES(NULL,'N6','Nomad Aviation (PTY) Ltd.');
INSERT INTO airlines VALUES(NULL,'HC','Aero-Tropics Air Services');
INSERT INTO airlines VALUES(NULL,'M7','Marsland Aviation');
INSERT INTO airlines VALUES(NULL,'Q4','Starlink Aviation');
INSERT INTO airlines VALUES(NULL,'GA','Garuda Indonesia');
INSERT INTO airlines VALUES(NULL,'IT','Tigerair Taiwan');
INSERT INTO airlines VALUES(NULL,'SK','Scandinavian Airlines');
INSERT INTO airlines VALUES(NULL,'HO','Juneyao Airlines');
INSERT INTO airlines VALUES(NULL,'OS','Austrian Airlines');
INSERT INTO airlines VALUES(NULL,'E7','Equaflight Service');
INSERT INTO airlines VALUES(NULL,'4C','LAN COLOMBIA AIRLINES');
INSERT INTO airlines VALUES(NULL,'HK','Skippers Aviation');
INSERT INTO airlines VALUES(NULL,'Q1','Sqiva Sistem');
INSERT INTO airlines VALUES(NULL,'8U','Afriqiyah Airways');
INSERT INTO airlines VALUES(NULL,'EF','Fly CamInter');
INSERT INTO airlines VALUES(NULL,'GL','Air Greenland');
INSERT INTO airlines VALUES(NULL,'H8','Hesa Airlines');
INSERT INTO airlines VALUES(NULL,'VA','Virgin Australia');
INSERT INTO airlines VALUES(NULL,'WZ','Red Wings Airlines');
INSERT INTO airlines VALUES(NULL,'9C','Spring Airlines');
INSERT INTO airlines VALUES('FlyArystan','0Y','FlyArystan');
INSERT INTO airlines VALUES(NULL,'6Z','Euro-Asia Air');
INSERT INTO airlines VALUES(NULL,'VN','Vietnam Airlines');
INSERT INTO airlines VALUES(NULL,'3R','Avior Airlines');
INSERT INTO airlines VALUES(NULL,'CU','Cubana de Aviación');
INSERT INTO airlines VALUES(NULL,'K4','ALS Ltd.');
INSERT INTO airlines VALUES(NULL,'HB','Asia Atlantic Airlines');
INSERT INTO airlines VALUES(NULL,'5T','Canadian North');
INSERT INTO airlines VALUES(NULL,'6Y','SmartLynx Airlines');
INSERT INTO airlines VALUES(NULL,'NJ','Aero VIP');
INSERT INTO airlines VALUES(NULL,'JJ','LATAM Brasil');
INSERT INTO airlines VALUES(NULL,'P5','Aerorepublica');
INSERT INTO airlines VALUES(NULL,'TW','T''way Air');
INSERT INTO airlines VALUES(NULL,'KL','KLM');
INSERT INTO airlines VALUES(NULL,'LK','Lao Skyway');
INSERT INTO airlines VALUES(NULL,'WW','WOW Air ehf');
INSERT INTO airlines VALUES(NULL,'IR','Iran Air');
INSERT INTO airlines VALUES(NULL,'ZN','NAYSA');
INSERT INTO airlines VALUES(NULL,'XC','Corendon Airlines');
INSERT INTO airlines VALUES(NULL,'PI','Polar Airlines');
INSERT INTO airlines VALUES(NULL,'GJ','Loong Air');
INSERT INTO airlines VALUES(NULL,'JS','Air Koryo');
INSERT INTO airlines VALUES(NULL,'KJ','Air Incheon');
INSERT INTO airlines VALUES(NULL,'PG','Bangkok Airways');
INSERT INTO airlines VALUES(NULL,'BB','Seaborne Airlines');
INSERT INTO airlines VALUES(NULL,'K6','Cambodia Angkor Air');
INSERT INTO airlines VALUES(NULL,'3E','Air Choice One');
INSERT INTO airlines VALUES(NULL,'CO','Cobalt Air');
INSERT INTO airlines VALUES(NULL,'M5','Kenmore Air');
INSERT INTO airlines VALUES(NULL,'Y7','NordStar');
INSERT INTO airlines VALUES(NULL,'ZZ','American Eagle');
INSERT INTO airlines VALUES(NULL,'C3','Trade Air');
INSERT INTO airlines VALUES(NULL,'DF','Condor');
INSERT INTO airlines VALUES(NULL,'NN','VIM Airlines');
INSERT INTO airlines VALUES(NULL,'SQ','Singapore Airlines');
INSERT INTO airlines VALUES(NULL,'EX','Thai Express Air Co. Ltd');
INSERT INTO airlines VALUES(NULL,'9U','Air Moldova');
INSERT INTO airlines VALUES(NULL,'E9','Evelop Airlines');
INSERT INTO airlines VALUES(NULL,'MH','Malaysia Airlines');
INSERT INTO airlines VALUES(NULL,'7P','Air Panama');
INSERT INTO airlines VALUES(NULL,'J6','Jet Ops');
INSERT INTO airlines VALUES(NULL,'SH','Sharp Airlines');
INSERT INTO airlines VALUES(NULL,'3A','Chu Kong Passenger Transport Co. Ltd.');
INSERT INTO airlines VALUES(NULL,'BJ','Nouvelair');
INSERT INTO airlines VALUES(NULL,'TI','Tailwind Airlines');
INSERT INTO airlines VALUES(NULL,'P9','Peruvian Airlines');
INSERT INTO airlines VALUES(NULL,'Y8','Yangtze River Express');
INSERT INTO airlines VALUES(NULL,'CL','Lufthansa CityLine');
INSERT INTO airlines VALUES(NULL,'ZB','Monarch Airlines');
INSERT INTO airlines VALUES(NULL,'V4','Vieques Air Link');
INSERT INTO airlines VALUES(NULL,'OG','Air Freight NZ');
INSERT INTO airlines VALUES(NULL,'SP','SATA Air Acores');
INSERT INTO airlines VALUES(NULL,'AC','Air Canada');
INSERT INTO airlines VALUES(NULL,'GU','Aviateca');
INSERT INTO airlines VALUES(NULL,'MB','MNG Airlines');
INSERT INTO airlines VALUES(NULL,'9M','Central Mountain Air');
INSERT INTO airlines VALUES(NULL,'M6','Amerijet International Inc.');
INSERT INTO airlines VALUES(NULL,'4X','Mercury Air Cargo, Inc.');
INSERT INTO airlines VALUES(NULL,'RM','Armenia Aircompany');
INSERT INTO airlines VALUES(NULL,'8A','Panama Airways');
INSERT INTO airlines VALUES(NULL,'6G','Sun Air Express');
INSERT INTO airlines VALUES(NULL,'GE','Transasia Airways');
INSERT INTO airlines VALUES(NULL,'CV','Cargolux');
INSERT INTO airlines VALUES(NULL,'ES','DHL Aviation EEMEA B.S.C.(c)');
INSERT INTO airlines VALUES(NULL,'UW','Uni-Top Airlines');
INSERT INTO airlines VALUES(NULL,'HE','LGW Luftfahrtgesellschaft Walter');
INSERT INTO airlines VALUES(NULL,'YO','Heli Air Monaco');
INSERT INTO airlines VALUES(NULL,'NP','Nile Air');
INSERT INTO airlines VALUES(NULL,'MY','Maya Island Air');
INSERT INTO airlines VALUES(NULL,'0M','Premier Airlines');
INSERT INTO airlines VALUES(NULL,'CR','OAG');
INSERT INTO airlines VALUES(NULL,'JY','InterCaribbean Airways');
INSERT INTO airlines VALUES(NULL,'K3','Taquan Air');
INSERT INTO airlines VALUES(NULL,'E6','Bringer Air Cargo');
INSERT INTO airlines VALUES(NULL,'1Z','Sabre Pacific');
INSERT INTO airlines VALUES(NULL,'BF','French Blue');
INSERT INTO airlines VALUES(NULL,'C7','Cinnamon Air');
INSERT INTO airlines VALUES(NULL,'7G','StarFlyer');
INSERT INTO airlines VALUES(NULL,'8M','Myanmar Airways International');
INSERT INTO airlines VALUES(NULL,'IL','PT.Trigana Air Service');
INSERT INTO airlines VALUES(NULL,'EA','East Horizon Airlines');
INSERT INTO airlines VALUES(NULL,'IN','NAM Air');
INSERT INTO airlines VALUES(NULL,'FF','Airshop B.V.');
INSERT INTO airlines VALUES(NULL,'JV','Bearskin Airlines');
INSERT INTO airlines VALUES(NULL,'VG','VLM Airlines');
INSERT INTO airlines VALUES(NULL,'H7','HiSky');
INSERT INTO airlines VALUES(NULL,'U5','Karinou Airlines');
INSERT INTO airlines VALUES(NULL,'F5','Aerotranscargo');
INSERT INTO airlines VALUES(NULL,'HI','Papillon Airways');
INSERT INTO airlines VALUES(NULL,'Y9','Kish Airlines');
INSERT INTO airlines VALUES(NULL,'AJ','Aztec Airways');
INSERT INTO airlines VALUES(NULL,'EK','Emirates');
INSERT INTO airlines VALUES(NULL,'OI','Hinterland Aviation');
INSERT INTO airlines VALUES(NULL,'FW','Ibex Airlines');
INSERT INTO airlines VALUES(NULL,'FQ','Brindabella Airlines');
INSERT INTO airlines VALUES(NULL,'7R','RusLine');
INSERT INTO airlines VALUES(NULL,'SS','Corsair International');
INSERT INTO airlines VALUES(NULL,'HG','Niki');
INSERT INTO airlines VALUES(NULL,'QH','Bamboo Airways');
INSERT INTO airlines VALUES(NULL,'G5','China Express Airlines');
INSERT INTO airlines VALUES(NULL,'XW','NokScoot');
INSERT INTO airlines VALUES(NULL,'LR','Avianca Costa Rica');
INSERT INTO airlines VALUES(NULL,'8D','FITS Aviation (Pvt) Ltd');
INSERT INTO airlines VALUES(NULL,'MK','Air Mauritius');
INSERT INTO airlines VALUES(NULL,'BA','British Airways');
INSERT INTO airlines VALUES(NULL,'TZ','Scoot');
INSERT INTO airlines VALUES(NULL,'TD','Atlantis European Airways');
INSERT INTO airlines VALUES(NULL,'EO','Pegas Fly');
INSERT INTO airlines VALUES(NULL,'WS','Westjet');
INSERT INTO airlines VALUES(NULL,'1L','Navitaire Open Skies');
INSERT INTO airlines VALUES(NULL,'CS','Continental Micronesia, Inc.');
INSERT INTO airlines VALUES(NULL,'RA','Royal Nepal Airlines');
INSERT INTO airlines VALUES(NULL,'5S','Global Aviation Services Group');
INSERT INTO airlines VALUES(NULL,'XR','Virgin Australia');
INSERT INTO airlines VALUES(NULL,'ZI','Aigle Azur');
INSERT INTO airlines VALUES(NULL,'US','US Airways');
INSERT INTO airlines VALUES(NULL,'W4','LC Busre SAC');
INSERT INTO airlines VALUES(NULL,'W3','Arik Air');
INSERT INTO airlines VALUES('Air Armenia','QN','Air Armenia');
INSERT INTO airlines VALUES(NULL,'HW','North-Wright Airways');
INSERT INTO airlines VALUES(NULL,'TP','TAP Portugal');
INSERT INTO airlines VALUES(NULL,'Y4','Volaris');
INSERT INTO airlines VALUES(NULL,'HY','Uzbekistan Airways');
INSERT INTO airlines VALUES(NULL,'MS','EgyptAir');
INSERT INTO airlines VALUES(NULL,'3J','Cargo Three Inc. dba Pan Air Cargo');
INSERT INTO airlines VALUES(NULL,'Q7','SkyBahamas Airlines');
INSERT INTO airlines VALUES(NULL,'XU','African Express Airways (K)  Limited');
INSERT INTO airlines VALUES(NULL,'VI','Volga-Dnepr Airlines');
INSERT INTO airlines VALUES(NULL,'MI','Silkair');
INSERT INTO airlines VALUES(NULL,'BS','US-Bangla Airlines');
INSERT INTO airlines VALUES(NULL,'86','Up Israel');
INSERT INTO airlines VALUES(NULL,'ET','Ethiopian Airlines');
INSERT INTO airlines VALUES(NULL,'CC','CM Airlines');
INSERT INTO airlines VALUES(NULL,'6M','Zacarias Moreno');
INSERT INTO airlines VALUES(NULL,'H6','Bulgarian Air Charter');
INSERT INTO airlines VALUES(NULL,'TY','Air Caledonie');
INSERT INTO airlines VALUES(NULL,'RB','Syrian Arab Airlines');
INSERT INTO airlines VALUES(NULL,'D6','Inter Air');
INSERT INTO airlines VALUES(NULL,'TQ','Tandem Aero');
INSERT INTO airlines VALUES(NULL,'UC','LAN Chile Cargo');
INSERT INTO airlines VALUES(NULL,'DD','Nok Air');
INSERT INTO airlines VALUES(NULL,'3S','Air Antilles Express');
INSERT INTO airlines VALUES(NULL,'TJ','Tradewind Aviation');
INSERT INTO airlines VALUES(NULL,'CA','Air China');
INSERT INTO airlines VALUES(NULL,'L6','Mauritania Airlines International');
INSERT INTO airlines VALUES(NULL,'XD','Air Transport Association of Americad\b\a Airlines for America');
INSERT INTO airlines VALUES(NULL,'A9','Georgian Airways');
INSERT INTO airlines VALUES(NULL,'VR','TACV Cabo Verde Airlines');
INSERT INTO airlines VALUES(NULL,'8F','STP Airways');
INSERT INTO airlines VALUES(NULL,'ZJ','Zambezi Airlines');
INSERT INTO airlines VALUES(NULL,'PQ','SkyUp Airlines');
INSERT INTO airlines VALUES(NULL,'9H','Chang An Airlines');
INSERT INTO airlines VALUES(NULL,'LJ','Jin Air');
INSERT INTO airlines VALUES(NULL,'J8','Berjaya Air');
INSERT INTO airlines VALUES(NULL,'6T','Air Mandalay');
INSERT INTO airlines VALUES(NULL,'EI','Aer Lingus');
INSERT INTO airlines VALUES(NULL,'6K','Kyrgyz Trans Avia');
INSERT INTO airlines VALUES(NULL,'FP','Servicios Aéreos de los Andes');
INSERT INTO airlines VALUES(NULL,'5F','Fly One');
INSERT INTO airlines VALUES(NULL,'IP','Apsara International Air');
INSERT INTO airlines VALUES(NULL,'1I','ChallengAir');
INSERT INTO airlines VALUES(NULL,'BL','Jetstar Pacific Airlines');
INSERT INTO airlines VALUES(NULL,'9E','Endeavor Air');
INSERT INTO airlines VALUES(NULL,'AQ','9 Air');
INSERT INTO airlines VALUES(NULL,'I5','AirAsia India');
INSERT INTO airlines VALUES(NULL,'C2','CEIBA Intercontinental');
INSERT INTO airlines VALUES(NULL,'6B','TUIfly Nordic');
INSERT INTO airlines VALUES(NULL,'OW','Skyward Express');
INSERT INTO airlines VALUES(NULL,'TF','BRA');
INSERT INTO airlines VALUES(NULL,'X9','Avion Express');
INSERT INTO airlines VALUES(NULL,'CN','Grand China Air');
INSERT INTO airlines VALUES(NULL,'UP','Bahamasair');
INSERT INTO airlines VALUES(NULL,'RS','Sky Regional Airlines');
INSERT INTO airlines VALUES(NULL,'QS','SmartWings');
INSERT INTO airlines VALUES(NULL,'5X','UPS');
INSERT INTO airlines VALUES(NULL,'WJ','Labrador Airways Limited');
INSERT INTO airlines VALUES(NULL,'DG','Tigerair Philippines');
INSERT INTO airlines VALUES(NULL,'1G','Travelport Global Distribution SystemB.V.');
INSERT INTO airlines VALUES(NULL,'WC','Islena de Inversiones S.A. de C.V.dba Islena Airlines');
INSERT INTO airlines VALUES(NULL,'X1','Fortune');
INSERT INTO airlines VALUES(NULL,'MR','Hunnu Air');
INSERT INTO airlines VALUES(NULL,'DT','TAAG Angola Airlines');
INSERT INTO airlines VALUES(NULL,'OQ','Chongqing Airlines');
INSERT INTO airlines VALUES(NULL,'JR','Joy Air');
INSERT INTO airlines VALUES(NULL,'DI','Norwegian Air');
INSERT INTO airlines VALUES(NULL,'KZ','Nippon Cargo Airlines');
INSERT INTO airlines VALUES(NULL,'WA','KLM Cityhopper');
INSERT INTO airlines VALUES(NULL,'AY','Finnair');
INSERT INTO airlines VALUES(NULL,'ZA','Skywings Asia Airlines Co., Ltd.');
INSERT INTO airlines VALUES(NULL,'9W','Jet Airways');
INSERT INTO airlines VALUES(NULL,'I2','Iberia Express');
INSERT INTO airlines VALUES(NULL,'K8','Kan Air');
INSERT INTO airlines VALUES(NULL,'7C','Jeju Air');
INSERT INTO airlines VALUES(NULL,'4N','Air North Charter and Training Ltd.');
INSERT INTO airlines VALUES(NULL,'P4','Aerolíneas Sosa');
INSERT INTO airlines VALUES(NULL,'JG','JETGO Australia');
INSERT INTO airlines VALUES(NULL,'KS','Penair');
INSERT INTO airlines VALUES(NULL,'0T','AnadoluJet');
INSERT INTO airlines VALUES(NULL,'AN','HOP!');
INSERT INTO airlines VALUES(NULL,'MP','Martinair');
INSERT INTO airlines VALUES(NULL,'CP','Compass Airlines');
INSERT INTO airlines VALUES(NULL,'2K','Avianca Ecuador');
INSERT INTO airlines VALUES(NULL,'R6','DOT LT');
INSERT INTO airlines VALUES(NULL,'G7','GoJet Airlines');
INSERT INTO airlines VALUES(NULL,'7Y','Mann Yadanarpon Airlines');
INSERT INTO airlines VALUES(NULL,'BG','Biman Bangladesh Airlines');
INSERT INTO airlines VALUES(NULL,'QM','Monacair');
INSERT INTO airlines VALUES(NULL,'O3','Orange Air, LLCN/A');
INSERT INTO airlines VALUES(NULL,'NA','Nesma Airlines');
INSERT INTO airlines VALUES(NULL,'5O','ASL Airlines France');
INSERT INTO airlines VALUES(NULL,'L4','Air Service Liege');
INSERT INTO airlines VALUES(NULL,'FH','Freebird Airlines');
INSERT INTO airlines VALUES(NULL,'P6','Pascan Aviation');
INSERT INTO airlines VALUES(NULL,'BV','Blue Panorama Airlines');
INSERT INTO airlines VALUES(NULL,'YM','Air Montenegro');
INSERT INTO airlines VALUES(NULL,'AL','Malta Air');
INSERT INTO airlines VALUES(NULL,'VZ','Thai Vietjet Air');
INSERT INTO airlines VALUES(NULL,'C6','CanJet');
INSERT INTO airlines VALUES(NULL,'0R','Renegade Air');
INSERT INTO airlines VALUES(NULL,'D3','Daallo Airlines');
INSERT INTO airlines VALUES(NULL,'PP','Jet Aviation Business');
INSERT INTO airlines VALUES(NULL,'Q5','40-Mile Air');
INSERT INTO airlines VALUES(NULL,'9F','Eurostar');
INSERT INTO airlines VALUES(NULL,'HA','Hawaiian Airlines');
INSERT INTO airlines VALUES(NULL,'ZH','Shenzhen Airlines');
INSERT INTO airlines VALUES(NULL,'VB','VivaAerobus');
INSERT INTO airlines VALUES(NULL,'2U','Sun d''Or International Airlines');
INSERT INTO airlines VALUES(NULL,'OO','SkyWest Airlines');
INSERT INTO airlines VALUES(NULL,'HU','Hainan Airlines');
INSERT INTO airlines VALUES(NULL,'7F','First Air');
INSERT INTO airlines VALUES(NULL,'QR','Qatar Airways');
INSERT INTO airlines VALUES(NULL,'2R','VIA Rail Canada Inc.');
INSERT INTO airlines VALUES(NULL,'V2','Vision Airlines');
INSERT INTO airlines VALUES(NULL,'WY','Oman Air');
INSERT INTO airlines VALUES(NULL,'SF','Tassili Airlines');
INSERT INTO airlines VALUES(NULL,'1X','Fly Branson Travel dba Branson AirExpress');
INSERT INTO airlines VALUES(NULL,'4V','Lignes Aeriennes Congolaises');
INSERT INTO airlines VALUES(NULL,'KU','Kuwait Airways');
INSERT INTO airlines VALUES(NULL,'U2','EasyJet');
INSERT INTO airlines VALUES(NULL,'WM','Winair');
INSERT INTO airlines VALUES(NULL,'5K','Hi Fly');
INSERT INTO airlines VALUES(NULL,'QX','Horizon Air');
INSERT INTO airlines VALUES(NULL,'5Y','Atlas Air');
INSERT INTO airlines VALUES(NULL,'KK','Atlas Global Airlines');
INSERT INTO airlines VALUES(NULL,'JD','Beijing Capital Airlines');
INSERT INTO airlines VALUES(NULL,'RE','Stobart Air');
INSERT INTO airlines VALUES(NULL,'7D','Maluti Sky');
INSERT INTO airlines VALUES(NULL,'BM','BMI Regional');
INSERT INTO airlines VALUES(NULL,'ТФ','Avia Traffic Company');
INSERT INTO airlines VALUES(NULL,'3Z','Travel Service Polska Sp. z.o.o.');
INSERT INTO airlines VALUES(NULL,'Z2','AirAsia Zest');
INSERT INTO airlines VALUES(NULL,'DL','Delta Air Lines');
INSERT INTO airlines VALUES(NULL,'LU','LAN Express');
INSERT INTO airlines VALUES(NULL,'L8','Afric Aviation');
INSERT INTO airlines VALUES(NULL,'KO','Komiaviatrans');
INSERT INTO airlines VALUES(NULL,'TR','Scoot');
INSERT INTO airlines VALUES(NULL,'F4','Air Flamenco');
INSERT INTO airlines VALUES(NULL,'X3','TUI fly');
INSERT INTO airlines VALUES(NULL,'MX','Mexicana de Aviación');
INSERT INTO airlines VALUES(NULL,'MO','Calm Air International');
INSERT INTO airlines VALUES(NULL,'AO','Australian Airlines');
INSERT INTO airlines VALUES(NULL,'6I','Air Alsie');
INSERT INTO airlines VALUES(NULL,'TA','TACA Airlines');
INSERT INTO airlines VALUES(NULL,'M8','SkyJet');
INSERT INTO airlines VALUES(NULL,'RY','Jiangxi Air');
INSERT INTO airlines VALUES(NULL,'A6','Air Alps Aviation');
INSERT INTO airlines VALUES(NULL,'B6','JetBlue Airways');
INSERT INTO airlines VALUES(NULL,'QW','Qingdao Airlines');
INSERT INTO airlines VALUES(NULL,'4E','Stabo Air Limited');
INSERT INTO airlines VALUES(NULL,'QF','Qantas');
INSERT INTO airlines VALUES(NULL,'7Q','Elite Airways');
INSERT INTO airlines VALUES(NULL,'N7','Nordic Regional Airline');
INSERT INTO airlines VALUES(NULL,'UG','Tunisair Express');
INSERT INTO airlines VALUES(NULL,'AU','Austral Lineas Aereas');
INSERT INTO airlines VALUES(NULL,'HX','Hong Kong Airlines');
INSERT INTO airlines VALUES(NULL,'VK','Level');
INSERT INTO airlines VALUES(NULL,'B1','TAB - Transportes Aéreos Bolivianos');
INSERT INTO airlines VALUES(NULL,'CY','Cyprus Airways');
INSERT INTO airlines VALUES(NULL,'NY','Air Iceland');
INSERT INTO airlines VALUES(NULL,'8T','Air Tindi');
INSERT INTO airlines VALUES(NULL,'AR','Aerolineas Argentinas');
INSERT INTO airlines VALUES(NULL,'DH','Douniah Airlines');
INSERT INTO airlines VALUES(NULL,'RU','AirBridgeCargo');
INSERT INTO airlines VALUES(NULL,'6D','Travel Service Slovensko');
INSERT INTO airlines VALUES(NULL,'5I','Alsa Grupo SLU');
INSERT INTO airlines VALUES(NULL,'0S','Sunday Express');
INSERT INTO airlines VALUES(NULL,'4Z','Airlink');
INSERT INTO airlines VALUES(NULL,'FB','Bulgaria Air');
INSERT INTO airlines VALUES(NULL,'EH','ANA Wings');

