CREATE TABLE countries (
   country_code TEXT,
   country_name TEXT,
   country_currency TEXT,
   country_name_translations_en TEXT,
   country_cases TEXT,
   country_cases_su TEXT,
   PRIMARY KEY (country_code)
);

INSERT INTO countries VALUES('GA','','XAF','Gabon',NULL,NULL);
INSERT INTO countries VALUES('AZ','Azerbaiyán','AZN','Azerbaijan',NULL,'Azerbaiyán');
INSERT INTO countries VALUES('IN','India','INR','India',NULL,'India');
INSERT INTO countries VALUES('KW','Kuwait','KWD','Kuwait',NULL,'Kuwait');
INSERT INTO countries VALUES('AR','Argentina','ARS','Argentina',NULL,'Argentina');
INSERT INTO countries VALUES('AW','Aruba','AWG','Aruba',NULL,'Aruba');
INSERT INTO countries VALUES('CX','Isla Christmas','AUD','Christmas Island',NULL,'Isla Christmas');
INSERT INTO countries VALUES('KM','Comoras','KMF','Comoros',NULL,'Comoras');
INSERT INTO countries VALUES('SL','Sierra Leona','SLL','Sierra Leone',NULL,'Sierra Leona');
INSERT INTO countries VALUES('AG','Antigua y Barbuda','XCD','Antigua and Barbuda',NULL,'Antigua y Barbuda');
INSERT INTO countries VALUES('AM','Armenia','AMD','Armenia',NULL,'Armenia');
INSERT INTO countries VALUES('NF','Isla Norfolk','AUD','Norfolk Island',NULL,'Isla Norfolk');
INSERT INTO countries VALUES('SG','Singapur','SGD','Singapore',NULL,'Singapur');
INSERT INTO countries VALUES('VC','San Vicente y las Granadinas','XCD','Saint Vincent and the Grenadines',NULL,'San Vicente y las Granadinas');
INSERT INTO countries VALUES('PF','Polinesia Francesa','XPF','French Polynesia',NULL,'Polinesia Francesa');
INSERT INTO countries VALUES('DK','Dinamarca','DKK','Denmark',NULL,'Dinamarca');
INSERT INTO countries VALUES('NA','Namibia','NAD','Namibia',NULL,'Namibia');
INSERT INTO countries VALUES('EG','Egipto','EGP','Egypt',NULL,'Egipto');
INSERT INTO countries VALUES('CM','Camerún','XAF','Cameroon',NULL,'Camerún');
INSERT INTO countries VALUES('GW','Guinea-Bisáu','XOF','Guinea-Bissau',NULL,'Guinea-Bisáu');
INSERT INTO countries VALUES('ST','Santo Tomé y Príncipe','STD','São Tomé and Príncipe',NULL,'Santo Tomé y Príncipe');
INSERT INTO countries VALUES('AO','Angola','AOA','Angola',NULL,'Angola');
INSERT INTO countries VALUES('KP','Corea del Norte','KPW','North Korea',NULL,'Corea del Norte');
INSERT INTO countries VALUES('TH','Tailandia','THB','Thailand',NULL,'Tailandia');
INSERT INTO countries VALUES('MC','Mónaco','EUR','Monaco',NULL,'Mónaco');
INSERT INTO countries VALUES('GG','Guernsey','GBP','Guernsey',NULL,'Guernsey');
INSERT INTO countries VALUES('BW','Botsuana','BWP','Botswana',NULL,'Botsuana');
INSERT INTO countries VALUES('US','EE. UU.','USD','United States',NULL,'EE. UU.');
INSERT INTO countries VALUES('IO','Territorio Británico del Océano Índico','USD','British Indian Ocean Territory',NULL,'Territorio Británico del Océano Índico');
INSERT INTO countries VALUES('SD','Sudán','SDG','Sudan',NULL,'Sudán');
INSERT INTO countries VALUES('SK','Eslovaquia','EUR','Slovakia',NULL,'Eslovaquia');
INSERT INTO countries VALUES('IL','Israel','ILS','Israel',NULL,'Israel');
INSERT INTO countries VALUES('NI','Nicaragua','NIO','Nicaragua',NULL,'Nicaragua');
INSERT INTO countries VALUES('ES','España','EUR','Spain',NULL,'España');
INSERT INTO countries VALUES('BH','Baréin','BHD','Bahrain',NULL,'Baréin');
INSERT INTO countries VALUES('DE','Alemania','EUR','Germany',NULL,'Alemania');
INSERT INTO countries VALUES('MP','Islas Marianas del Norte','USD','Northern Mariana Islands',NULL,'Islas Marianas del Norte');
INSERT INTO countries VALUES('HU','Hungría','HUF','Hungary',NULL,'Hungría');
INSERT INTO countries VALUES('GE','Georgia','GEL','Georgia',NULL,'Georgia');
INSERT INTO countries VALUES('NO','Noruega','NOK','Norway',NULL,'Noruega');
INSERT INTO countries VALUES('BQ','Caribe neerlandés','USD','Caribbean Netherlands',NULL,'Caribe neerlandés');
INSERT INTO countries VALUES('VG','Islas Vírgenes Británicas','USD','British Virgin Islands',NULL,'Islas Vírgenes Británicas');
INSERT INTO countries VALUES('PS','Palestina','ILS','Palestine',NULL,'Palestina');
INSERT INTO countries VALUES('BR','Brasil','BRL','Brazil',NULL,'Brasil');
INSERT INTO countries VALUES('RE','Reunión','EUR','Réunion',NULL,'Reunión');
INSERT INTO countries VALUES('UG','Uganda','UGX','Uganda',NULL,'Uganda');
INSERT INTO countries VALUES('YT','Mayotte','EUR','Mayotte',NULL,'Mayotte');
INSERT INTO countries VALUES('CU','Cuba','CUP','Cuba',NULL,'Cuba');
INSERT INTO countries VALUES('LC','Santa Lucía','XCD','Saint Lucia',NULL,'Santa Lucía');
INSERT INTO countries VALUES('JE','Jersey','GBP','Jersey',NULL,'Jersey');
INSERT INTO countries VALUES('SH','Santa Elena, Ascensión y Tristán de Acuña','SHP','Saint Helena, Ascension and Tristan da Cunha',NULL,'Santa Elena, Ascensión y Tristán de Acuña');
INSERT INTO countries VALUES('AL','Albania','ALL','Albania',NULL,'Albania');
INSERT INTO countries VALUES('WS','Samoa','WST','Samoa',NULL,'Samoa');
INSERT INTO countries VALUES('IQ','Iraq','IQD','Iraq',NULL,'Iraq');
INSERT INTO countries VALUES('BO','Bolivia','BOB','Bolivia',NULL,'Bolivia');
INSERT INTO countries VALUES('IE','Irlanda','EUR','Ireland',NULL,'Irlanda');
INSERT INTO countries VALUES('BZ','Belice','BZD','Belize',NULL,'Belice');
INSERT INTO countries VALUES('ME','Montenegro','EUR','Montenegro',NULL,'Montenegro');
INSERT INTO countries VALUES('BT','Bután','BTN','Bhutan',NULL,'Bután');
INSERT INTO countries VALUES('EC','Ecuador','USD','Ecuador',NULL,'Ecuador');
INSERT INTO countries VALUES('YE','Yemen','YER','Yemen',NULL,'Yemen');
INSERT INTO countries VALUES('KG','Kirguistán','KGS','Kyrgyzstan',NULL,'Kirguistán');
INSERT INTO countries VALUES('TC','Islas Turcas y Caicos','USD','Turks and Caicos Islands',NULL,'Islas Turcas y Caicos');
INSERT INTO countries VALUES('CY','Chipre','EUR','Cyprus',NULL,'Chipre');
INSERT INTO countries VALUES('NP','Nepal','NPR','Nepal',NULL,'Nepal');
INSERT INTO countries VALUES('MG','Madagascar','MGA','Madagascar',NULL,'Madagascar');
INSERT INTO countries VALUES('TW','Taiwán','TWD','Taiwan',NULL,'Taiwán');
INSERT INTO countries VALUES('KR','Corea del Sur','KRW','South Korea',NULL,'Corea del Sur');
INSERT INTO countries VALUES('AD','Andorra','EUR','Andorra',NULL,'Andorra');
INSERT INTO countries VALUES('GH','Ghana','GHS','Ghana',NULL,'Ghana');
INSERT INTO countries VALUES('VI','Islas Vírgenes de los Estados Unidos','USD','U.S. Virgin Islands',NULL,'Islas Vírgenes de los Estados Unidos');
INSERT INTO countries VALUES('BM','Bermudas','BMD','Bermuda',NULL,'Bermudas');
INSERT INTO countries VALUES('CA','Canadá','CAD','Canada',NULL,'Canadá');
INSERT INTO countries VALUES('MU','Mauricio','MUR','Mauritius',NULL,'Mauricio');
INSERT INTO countries VALUES('TG','Togo','XOF','Togo',NULL,'Togo');
INSERT INTO countries VALUES('PH','Filipinas','PHP','Philippines',NULL,'Filipinas');
INSERT INTO countries VALUES('TF','Territorios Australes Franceses','EUR','French Southern Territories',NULL,'Territorios Australes Franceses');
INSERT INTO countries VALUES('TV','Tuvalu','AUD','Tuvalu',NULL,'Tuvalu');
INSERT INTO countries VALUES('SM','San Marino','EUR','San Marino',NULL,'San Marino');
INSERT INTO countries VALUES('LV','Letonia','EUR','Latvia',NULL,'Letonia');
INSERT INTO countries VALUES('CI','Costa de Marfil','XOF','Ivory Coast',NULL,'Costa de Marfil');
INSERT INTO countries VALUES('LI','Liechtenstein','CHF','Liechtenstein',NULL,'Liechtenstein');
INSERT INTO countries VALUES('TT','Trinidad y Tobago','TTD','Trinidad and Tobago',NULL,'Trinidad y Tobago');
INSERT INTO countries VALUES('SN','Senegal','XOF','Senegal',NULL,'Senegal');
INSERT INTO countries VALUES('PL','Polonia','PLN','Poland',NULL,'Polonia');
INSERT INTO countries VALUES('MO','Macao','MOP','Macau',NULL,'Macao');
INSERT INTO countries VALUES('TO','Tonga','TOP','Tonga',NULL,'Tonga');
INSERT INTO countries VALUES('AS','Samoa Americana','USD','American Samoa',NULL,'Samoa Americana');
INSERT INTO countries VALUES('CD','República Democrática del Congo','CDF','Democratic Republic of the Congo',NULL,'República Democrática del Congo');
INSERT INTO countries VALUES('PN','Islas Pitcairn','NZD','Pitcairn Islands',NULL,'Islas Pitcairn');
INSERT INTO countries VALUES('TL','Timor Oriental','USD','East Timor',NULL,'Timor Oriental');
INSERT INTO countries VALUES('BJ','Benín','XOF','Benin',NULL,'Benín');
INSERT INTO countries VALUES('ZM','Zambia','ZMK','Zambia',NULL,'Zambia');
INSERT INTO countries VALUES('SV','El Salvador','USD','El Salvador',NULL,'El Salvador');
INSERT INTO countries VALUES('FO','Islas Feroe','DKK','Faroe Islands',NULL,'Islas Feroe');
INSERT INTO countries VALUES('EE','Estonia','EUR','Estonia',NULL,'Estonia');
INSERT INTO countries VALUES('BG','Bulgaria','BGN','Bulgaria',NULL,'Bulgaria');
INSERT INTO countries VALUES('RU','Rusia','RUB','Russia',NULL,'Rusia');
INSERT INTO countries VALUES('FI','Finlandia','EUR','Finland',NULL,'Finlandia');
INSERT INTO countries VALUES('TN','Túnez','TND','Tunisia',NULL,'Túnez');
INSERT INTO countries VALUES('SY','Siria','SYP','Syria',NULL,'Siria');
INSERT INTO countries VALUES('TZ','Tanzania','TZS','Tanzania',NULL,'Tanzania');
INSERT INTO countries VALUES('FK','Islas Malvinas','FKP','Falkland Islands',NULL,'Islas Malvinas');
INSERT INTO countries VALUES('TK','Tokelau','NZD','Tokelau',NULL,'Tokelau');
INSERT INTO countries VALUES('SX','Sint Maarten','ANG','Sint Maarten',NULL,'Sint Maarten');
INSERT INTO countries VALUES('PE','Perú','PEN','Peru',NULL,'Perú');
INSERT INTO countries VALUES('TR','Turquía','TRY','Turkey',NULL,'Turquía');
INSERT INTO countries VALUES('CG','República del Congo','XAF','Republic of the Congo',NULL,'República del Congo');
INSERT INTO countries VALUES('CN','China','CNY','China',NULL,'China');
INSERT INTO countries VALUES('BI','Burundi','BIF','Burundi',NULL,'Burundi');
INSERT INTO countries VALUES('RO','Rumanía','RON','Romania',NULL,'Rumanía');
INSERT INTO countries VALUES('CL','Chile','CLP','Chile',NULL,'Chile');
INSERT INTO countries VALUES('ER','Eritrea','ERN','Eritrea',NULL,'Eritrea');
INSERT INTO countries VALUES('BD','Bangladés','BDT','Bangladesh',NULL,'Bangladés');
INSERT INTO countries VALUES('LR','Liberia','LRD','Liberia',NULL,'Liberia');
INSERT INTO countries VALUES('TJ','Tayikistán','TJS','Tajikistan',NULL,'Tayikistán');
INSERT INTO countries VALUES('DJ','Yibuti','DJF','Djibouti',NULL,'Yibuti');
INSERT INTO countries VALUES('NR','Nauru','AUD','Nauru',NULL,'Nauru');
INSERT INTO countries VALUES('MW','Malaui','MWK','Malawi',NULL,'Malaui');
INSERT INTO countries VALUES('JM','Jamaica','JMD','Jamaica',NULL,'Jamaica');
INSERT INTO countries VALUES('DZ','Argelia','DZD','Algeria',NULL,'Argelia');
INSERT INTO countries VALUES('FJ','Fiyi','FJD','Fiji',NULL,'Fiyi');
INSERT INTO countries VALUES('BB','Barbados','BBD','Barbados',NULL,'Barbados');
INSERT INTO countries VALUES('CH','Suiza','CHF','Switzerland',NULL,'Suiza');
INSERT INTO countries VALUES('AU','Australia','AUD','Australia',NULL,'Australia');
INSERT INTO countries VALUES('MD','Moldavia','MDL','Moldova',NULL,'Moldavia');
INSERT INTO countries VALUES('PY','Paraguay','PYG','Paraguay',NULL,'Paraguay');
INSERT INTO countries VALUES('TM','Turkmenistán','TMT','Turkmenistan',NULL,'Turkmenistán');
INSERT INTO countries VALUES('GN','Guinea','GNF','Guinea',NULL,'Guinea');
INSERT INTO countries VALUES('NE','Níger','XOF','Niger',NULL,'Níger');
INSERT INTO countries VALUES('AX','Islas Åland','EUR','Åland Islands',NULL,'Islas Åland');
INSERT INTO countries VALUES('AI','Anguila','XCD','Anguilla',NULL,'Anguila');
INSERT INTO countries VALUES('MV','Maldivas','MVR','Maldives',NULL,'Maldivas');
INSERT INTO countries VALUES('GY','Guyana','GYD','Guyana',NULL,'Guyana');
INSERT INTO countries VALUES('JP','Japón','JPY','Japan',NULL,'Japón');
INSERT INTO countries VALUES('BN','Brunéi','BND','Brunei',NULL,'Brunéi');
INSERT INTO countries VALUES('NZ','Nueva Zelanda','NZD','New Zealand',NULL,'Nueva Zelanda');
INSERT INTO countries VALUES('LU','Luxemburgo','EUR','Luxembourg',NULL,'Luxemburgo');
INSERT INTO countries VALUES('AQ','Antártida','','Antarctica',NULL,'Antártida');
INSERT INTO countries VALUES('SC','Seychelles','SCR','Seychelles',NULL,'Seychelles');
INSERT INTO countries VALUES('OM','Omán','OMR','Oman',NULL,'Omán');
INSERT INTO countries VALUES('MK','Macedonia del Norte','MKD','North Macedonia',NULL,'Macedonia del Norte');
INSERT INTO countries VALUES('CV','Cabo Verde','CVE','Cape Verde',NULL,'Cabo Verde');
INSERT INTO countries VALUES('ET','Etiopía','ETB','Ethiopia',NULL,'Etiopía');
INSERT INTO countries VALUES('GQ','Guinea Ecuatorial','XAF','Equatorial Guinea',NULL,'Guinea Ecuatorial');
INSERT INTO countries VALUES('CW','Curazao','ANG','Curaçao',NULL,'Curazao');
INSERT INTO countries VALUES('GS','Islas Georgia del Sur y Sandwich del Sur','GBP','South Georgia and the South Sandwich Islands',NULL,'Islas Georgia del Sur y Sandwich del Sur');
INSERT INTO countries VALUES('ML','Mali','XOF','Mali',NULL,'Mali');
INSERT INTO countries VALUES('PA','Panamá','PAB','Panama',NULL,'Panamá');
INSERT INTO countries VALUES('RS','Serbia','RSD','Serbia',NULL,'Serbia');
INSERT INTO countries VALUES('HT','Haití','HTG','Haiti',NULL,'Haití');
INSERT INTO countries VALUES('BF','Burkina Faso','XOF','Burkina Faso',NULL,'Burkina Faso');
INSERT INTO countries VALUES('SZ','Suazilandia','SZL','Eswatini',NULL,'Suazilandia');
INSERT INTO countries VALUES('BA','Bosnia y Herzegovina','BAM','Bosnia and Herzegovina',NULL,'Bosnia y Herzegovina');
INSERT INTO countries VALUES('TD','Chad','XAF','Chad',NULL,'Chad');
INSERT INTO countries VALUES('MR','Mauritania','MRO','Mauritania',NULL,'Mauritania');
INSERT INTO countries VALUES('SS','Sudán del Sur','','South Sudan',NULL,'Sudán del Sur');
INSERT INTO countries VALUES('BY','Bielorrusia','BYN','Belarus',NULL,'Bielorrusia');
INSERT INTO countries VALUES('MA','Marruecos','MAD','Morocco',NULL,'Marruecos');
INSERT INTO countries VALUES('PR','Puerto Rico','USD','Puerto Rico',NULL,'Puerto Rico');
INSERT INTO countries VALUES('CK','Islas Cook','NZD','Cook Islands',NULL,'Islas Cook');
INSERT INTO countries VALUES('PM','San Pedro y Miquelón','EUR','Saint Pierre and Miquelon',NULL,'San Pedro y Miquelón');
INSERT INTO countries VALUES('MQ','Martinica','EUR','Martinique',NULL,'Martinica');
INSERT INTO countries VALUES('LB','Líbano','LBP','Lebanon',NULL,'Líbano');
INSERT INTO countries VALUES('BL','San Bartolomé','EUR','Saint Barthélemy',NULL,'San Bartolomé');
INSERT INTO countries VALUES('LT','Lituania','EUR','Lithuania',NULL,'Lituania');
INSERT INTO countries VALUES('BE','Bélgica','EUR','Belgium',NULL,'Bélgica');
INSERT INTO countries VALUES('KH','Camboya','KHR','Cambodia',NULL,'Camboya');
INSERT INTO countries VALUES('BS','Bahamas','BSD','Bahamas',NULL,'Bahamas');
INSERT INTO countries VALUES('AT','Austria','EUR','Austria',NULL,'Austria');
INSERT INTO countries VALUES('SA','Arabia Saudí','SAR','Saudi Arabia',NULL,'Arabia Saudí');
INSERT INTO countries VALUES('PT','Portugal','EUR','Portugal',NULL,'Portugal');
INSERT INTO countries VALUES('MH','Islas Marshall','USD','Marshall Islands',NULL,'Islas Marshall');
INSERT INTO countries VALUES('CZ','República Checa','CZK','Czech Republic',NULL,'República Checa');
INSERT INTO countries VALUES('WF','Wallis y Futuna','XPF','Wallis and Futuna',NULL,'Wallis y Futuna');
INSERT INTO countries VALUES('SI','Eslovenia','EUR','Slovenia',NULL,'Eslovenia');
INSERT INTO countries VALUES('NC','Nueva Caledonia','XPF','New Caledonia',NULL,'Nueva Caledonia');
INSERT INTO countries VALUES('GR','Grecia','EUR','Greece',NULL,'Grecia');
INSERT INTO countries VALUES('LK','Sri Lanka','LKR','Sri Lanka',NULL,'Sri Lanka');
INSERT INTO countries VALUES('HM','Islas Heard y McDonald','AUD','Heard Island and McDonald Islands',NULL,'Islas Heard y McDonald');
INSERT INTO countries VALUES('UA','Ucrania','UAH','Ukraine',NULL,'Ucrania');
INSERT INTO countries VALUES('KI','Kiribati','AUD','Kiribati',NULL,'Kiribati');
INSERT INTO countries VALUES('PW','Palau','USD','Palau',NULL,'Palau');
INSERT INTO countries VALUES('ZW','Zimbabue','ZWD','Zimbabwe',NULL,'Zimbabue');
INSERT INTO countries VALUES('KY','Islas Caimán','KYD','Cayman Islands',NULL,'Islas Caimán');
INSERT INTO countries VALUES('KE','Kenia','KES','Kenya',NULL,'Kenia');
INSERT INTO countries VALUES('SB','Islas Salomón','SBD','Solomon Islands',NULL,'Islas Salomón');
INSERT INTO countries VALUES('LY','Libia','LYD','Libya',NULL,'Libia');
INSERT INTO countries VALUES('IS','Islandia','ISK','Iceland',NULL,'Islandia');
INSERT INTO countries VALUES('CF','República Centroafricana','XAF','Central African Republic',NULL,'República Centroafricana');
INSERT INTO countries VALUES('KZ','Kazajistán','KZT','Kazakhstan',NULL,'Kazajistán');
INSERT INTO countries VALUES('GM','Gambia','GMD','Gambia',NULL,'Gambia');
INSERT INTO countries VALUES('SE','Suecia','SEK','Sweden',NULL,'Suecia');
INSERT INTO countries VALUES('GB','Reino Unido','GBP','United Kingdom',NULL,'Reino Unido');
INSERT INTO countries VALUES('HR','Croacia','HRK','Croatia',NULL,'Croacia');
INSERT INTO countries VALUES('SJ','Svalbard y Jan Mayen','NOK','Svalbard and Jan Mayen',NULL,'Svalbard y Jan Mayen');
INSERT INTO countries VALUES('GI','Gibraltar','GIP','Gibraltar',NULL,'Gibraltar');
INSERT INTO countries VALUES('KX','Crimea','','Crimea',NULL,'Crimea');
INSERT INTO countries VALUES('GL','Groenlandia','DKK','Greenland',NULL,'Groenlandia');
INSERT INTO countries VALUES('FR','Francia','EUR','France',NULL,'Francia');
INSERT INTO countries VALUES('VE','Venezuela','VEF','Venezuela',NULL,'Venezuela');
INSERT INTO countries VALUES('MN','Mongolia','MNT','Mongolia',NULL,'Mongolia');
INSERT INTO countries VALUES('QA','Catar','QAR','Qatar',NULL,'Catar');
INSERT INTO countries VALUES('ID','Indonesia','IDR','Indonesia',NULL,'Indonesia');
INSERT INTO countries VALUES('RW','Ruanda','RWF','Rwanda',NULL,'Ruanda');
INSERT INTO countries VALUES('IT','','EUR','Italy',NULL,NULL);
INSERT INTO countries VALUES('DO','República Dominicana','DOP','Dominican Republic',NULL,'República Dominicana');
INSERT INTO countries VALUES('LS','Lesoto','LSL','Lesotho',NULL,'Lesoto');
INSERT INTO countries VALUES('UY','Uruguay','UYU','Uruguay',NULL,'Uruguay');
INSERT INTO countries VALUES('FM','Micronesia','USD','Micronesia',NULL,'Micronesia');
INSERT INTO countries VALUES('ZA','Sudáfrica','ZAR','South Africa',NULL,'Sudáfrica');
INSERT INTO countries VALUES('AF','Afganistán','AFN','Afghanistan',NULL,'Afganistán');
INSERT INTO countries VALUES('KN','San Cristóbal y Nieves','XCD','Saint Kitts and Nevis',NULL,'San Cristóbal y Nieves');
INSERT INTO countries VALUES('NU','Isla Niue','NZD','Niue',NULL,'Isla Niue');
INSERT INTO countries VALUES('VN','Vietnam','VND','Vietnam',NULL,'Vietnam');
INSERT INTO countries VALUES('MZ','Mozambique','MZN','Mozambique',NULL,'Mozambique');
INSERT INTO countries VALUES('MS','Montserrat','XCD','Montserrat',NULL,'Montserrat');
INSERT INTO countries VALUES('PK','Pakistán','PKR','Pakistan',NULL,'Pakistán');
INSERT INTO countries VALUES('GD','Granada','XCD','Grenada',NULL,'Granada');
INSERT INTO countries VALUES('GT','Guatemala','GTQ','Guatemala',NULL,'Guatemala');
INSERT INTO countries VALUES('EH','Sáhara Occidental','MAD','Western Sahara',NULL,'Sáhara Occidental');
INSERT INTO countries VALUES('SR','Surinam','SRD','Suriname',NULL,'Surinam');
INSERT INTO countries VALUES('AE','Emiratos Árabes Unidos','AED','United Arab Emirates',NULL,'Emiratos Árabes Unidos');
INSERT INTO countries VALUES('MX','México','MXN','Mexico',NULL,'México');
INSERT INTO countries VALUES('PG','Papúa Nueva Guinea','PGK','Papua New Guinea',NULL,'Papúa Nueva Guinea');
INSERT INTO countries VALUES('CR','Costa Rica','CRC','Costa Rica',NULL,'Costa Rica');
INSERT INTO countries VALUES('JO','Jordania','JOD','Jordan',NULL,'Jordania');
INSERT INTO countries VALUES('MM','Myanmar','MMK','Myanmar',NULL,'Myanmar');
INSERT INTO countries VALUES('VA','Ciudad del Vaticano','EUR','Vatican City',NULL,'Ciudad del Vaticano');
INSERT INTO countries VALUES('HN','Honduras','HNL','Honduras',NULL,'Honduras');
INSERT INTO countries VALUES('MF','San Martín','EUR','Saint Martin',NULL,'San Martín');
INSERT INTO countries VALUES('GP','Guadalupe','EUR','Guadeloupe',NULL,'Guadalupe');
INSERT INTO countries VALUES('GF','Guayana Francesa','EUR','French Guiana',NULL,'Guayana Francesa');
INSERT INTO countries VALUES('UZ','Uzbekistán','UZS','Uzbekistan',NULL,'Uzbekistán');
INSERT INTO countries VALUES('XK','Kosovo','EUR','Kosovo',NULL,'Kosovo');
INSERT INTO countries VALUES('LA','Laos','LAK','Laos',NULL,'Laos');
INSERT INTO countries VALUES('SO','Somalia','SOS','Somalia',NULL,'Somalia');
INSERT INTO countries VALUES('IR','Irán','IRR','Iran',NULL,'Irán');
INSERT INTO countries VALUES('GU','Guam','USD','Guam',NULL,'Guam');
INSERT INTO countries VALUES('UM','Islas menores alejadas de los Estados Unidos','USD','United States Minor Outlying Islands',NULL,'Islas menores alejadas de los Estados Unidos');
INSERT INTO countries VALUES('VU','Vanuatu','VUV','Vanuatu',NULL,'Vanuatu');
INSERT INTO countries VALUES('NG','Nigeria','NGN','Nigeria',NULL,'Nigeria');
INSERT INTO countries VALUES('DM','Dominica','XCD','Dominica',NULL,'Dominica');
INSERT INTO countries VALUES('NL','Países Bajos','EUR','Netherlands',NULL,'Países Bajos');
INSERT INTO countries VALUES('HK','Hong Kong','HKD','Hong Kong',NULL,'Hong Kong');
INSERT INTO countries VALUES('CO','Colombia','COP','Colombia',NULL,'Colombia');
INSERT INTO countries VALUES('BV','Isla Bouvet','NOK','Bouvet Island',NULL,'Isla Bouvet');
INSERT INTO countries VALUES('MT','Malta','EUR','Malta',NULL,'Malta');
INSERT INTO countries VALUES('CC','Islas Cocos','AUD','Cocos (Keeling) Islands',NULL,'Islas Cocos');
INSERT INTO countries VALUES('MY','Malasia','MYR','Malaysia',NULL,'Malasia');
INSERT INTO countries VALUES('IM','Isla de Man','GBP','Isle of Man',NULL,'Isla de Man');
